import { Divider, Grid, Paper, TextField } from "@material-ui/core";
import React, { useEffect, useState } from "react";
import { Button, MultiSelect, NumberInput, Text } from "@mantine/core";
import { useDispatch, useSelector } from "react-redux";

import "./Search.css";
import { searchAdvMovies } from "../../../actions/movies";
import { Link } from "react-router-dom";
const defaultQuery = { title: "", year: undefined };
const defaultGenres = [
	"Action",
	"Adventure",
	"Animated",
	"Biography",
	"Comedy",
	"Crime",
	"Dance",
	"Disaster",
	"Documentary",
	"Drama",
	"Erotic",
	"Family",
	"Fantasy",
	"Found Footage",
	"Historical",
	"Horror",
	"Independent",
	"Legal",
	"Live Action",
	"Martial Arts",
	"Musical",
	"Mystery",
	"Noir",
	"Performance",
	"Political",
	"Romance",
	"Satire",
	"Sci-Fi",
	"Short",
	"Silent",
	"Slasher",
	"Sports",
	"Spy",
	"Superhero",
	"Supernatural",
	"Suspense",
	"Teen",
	"Thriller",
	"War",
	"Western",
];
const defaultActors = [
	"Robert De Niro",
	"Jack Nicholson",
	"Marlon Brando",
	"Denzel Washington",
	"Katharine Hepburn",
	"Humphrey Bogart",
	"Meryl Streep",
	"Daniel Day-Lewis",
	"Sidney Poitier",
	"Clark Gable",
	"Ingrid Bergman",
	"Tom Hanks",
	"Elizabeth Taylor",
	"Bette Davis",
	"Gregory Peck",
	"Leonardo DiCaprio",
	"Cate Blanchett",
	"Audrey Hepburn",
	"Spencer Tracy",
	"Kate Winslet",
	"Shah Rukh Khan",
	"Viola Davis",
	"Sophia Loren",
	"Cary Grant",
	"Vivien Leigh",
	"Marilyn Monroe",
	"Laurence Olivier",
	"James Stewart",
	"Steve McQueen",
	"Diane Keaton",
	"Julia Roberts",
	"Jodie Foster",
	"Judy Garland",
	"Morgan Freeman",
	"Paul Newman",
	"Henry Fonda",
	"Catherine Deneuve",
	"Grace Kelly",
	"Helen Mirren",
	"James Cagney",
	"Angela Bassett",
	"Johnny Depp",
	"Greta Garbo",
	"Olivia de Havilland",
	"Charles Chaplin",
	"Setsuko Hara",
	"Julie Andrews",
	"Montgomery Clift",
	"Isabelle Huppert",
	"Al Pacino",
	"Rita Hayworth",
	"Halle Berry",
	"James Dean",
	"Kirk Douglas",
	"Natalie Wood",
	"Marcello Mastroianni",
	"Joan Crawford",
	"Harrison Ford",
	"Susan Sarandon",
	"Gene Kelly",
	"Glenn Close",
	"Joan Fontaine",
	"Julianne Moore",
	"Will Smith",
	"Bruce Lee",
	"Regina King",
	"Angelina Jolie",
	"John Wayne",
	"Jane Fonda",
	"Charlton Heston",
	"Gary Cooper",
	"Anthony Hopkins",
	"Liv Ullmann",
	"Natalie Portman",
	"Gérard Depardieu",
	"Forest Whitaker",
	"Sandra Bullock",
	"Deborah Kerr",
	"Toshirô Mifune",
	"Dustin Hoffman",
	"Mohanlal",
	"Emma Thompson",
	"Tom Cruise",
	"Michelle Pfeiffer",
	"Faye Dunaway",
	"Samuel L. Jackson",
	"Peter O'Toole",
	"Heath Ledger",
	"Penélope Cruz",
	"Nicole Kidman",
	"Chadwick Boseman",
	"Antonio Banderas",
	"Sigourney Weaver",
	"Salma Hayek",
	"Don Cheadle",
	"Frances McDormand",
	"Kathy Bates",
	"Omar Sharif",
	"Amy Adams",
	"Joaquin Phoenix",
	"Jeff Bridges",
	"Ben Kingsley",
	"Tommy Lee Jones",
	"Robert Redford",
	"Jack Lemmon",
	"Christopher Plummer",
	"George C. Scott",
	"Robin Williams",
	"Christopher Walken",
	"Philip Seymour Hoffman",
	"George Clooney",
	"Gene Hackman",
	"Bruce Willis",
	"Sean Connery",
	"Ian McKellen",
	"Russell Crowe",
	"Bill Murray",
	"Nicolas Cage",
	"Joe Pesci",
	"Brad Pitt",
	"Kevin Costner",
	"Donald Sutherland",
	"Clint Eastwood",
	"Michael Douglas",
	"Robert Downey Jr.",
	"Ava Gardner",
	"Sally Field",
	"Doris Day",
	"Shirley MacLaine",
	"Holly Hunter",
	"Hilary Swank",
	"Claudette Colbert",
	"Diane Lane",
	"Jessica Lange",
	"Gloria Swanson",
	"Lauren Bacall",
	"Lucy Liu",
	"Norma Shearer",
	"Bette Midler",
	"Mary Tyler Moore",
	"Anna Magnani",
	"Judi Dench",
	"Sharon Stone",
	"Kim Basinger",
	"Glenda Jackson",
	"Donna Reed",
	"Demi Moore",
	"Anne Hathaway",
	"Liza Minnelli",
	"Geena Davis",
	"Peter Sellers",
	"Woody Allen",
	"Mel Gibson",
	"Jim Carrey",
	"Mark Wahlberg",
	"Steve Martin",
	"Javier Bardem",
	"Christoph Waltz",
	"Tim Robbins",
	"Arnold Schwarzenegger",
	"Sylvester Stallone",
	"Viggo Mortensen",
	"Christopher Lee",
	"Geoffrey Rush",
	"Alec Guinness",
	"Richard Burton",
	"Alec Baldwin",
	"James Caan",
	"Chiwetel Ejiofor",
	"Mads Mikkelsen",
	"Ben Stiller",
	"Willem Dafoe",
	"Ed Harris",
	"Harvey Keitel",
	"Jon Voight",
	"Drew Barrymore",
	"Winona Ryder",
	"Kathleen Turner",
	"Uma Thurman",
	"Rene Russo",
	"Whoopi Goldberg",
	"Annette Bening",
	"Maggie Smith",
	"Barbra Streisand",
	"Jennifer Lawrence",
	"Joanne Woodward",
	"Mercedes McCambridge",
	"Anjelica Huston",
	"Dianne Wiest",
	"Goldie Hawn",
	"Claudia Cardinale",
	"Gwyneth Paltrow",
	"Charlize Theron",
	"Debra Winger",
	"Marion Cotillard",
	"Christina Ricci",
	"Juliette Binoche",
	"Daryl Hannah",
	"Shirley Booth",
	"Reese Witherspoon",
	"Benicio Del Toro",
	"Kevin Bacon",
	"Patrick Swayze",
	"Michael Caine",
	"Robert Duvall",
	"Burt Lancaster",
	"Robert Mitchum",
	"Colin Farrell",
	"William Holden",
	"Edward G. Robinson",
	"William Powell",
	"Jared Leto",
	"Errol Flynn",
	"Groucho Marx",
	"James Mason",
	"Buster Keaton",
	"Orson Welles",
	"Fred Astaire",
	"Bradley Cooper",
	"Gary Oldman",
	"Jude Law",
	"Paul Giamatti",
	"Liam Neeson",
	"Matt Damon",
	"Michael Fassbender",
	"Carol Burnett",
	"Jessica Tandy",
	"Helen Hunt",
	"Patricia Arquette",
	"Carmen Miranda",
	"Kate Hudson",
	"Catherine Zeta-Jones",
	"Cameron Diaz",
	"Debbie Reynolds",
	"Ellen Burstyn",
	"Maureen O'Hara",
	"Myrna Loy",
	"Lena Headey",
	"Toni Collette",
	"Laura Linney",
	"Marlene Dietrich",
	"Carole Lombard",
	"Jean Arthur",
	"Jean Harlow",
	"Ginger Rogers",
	"Mary Pickford",
	"Mae West",
	"Gillian Anderson",
	"Emma Watson",
	"Meg Ryan",
	"Alan Arkin",
	"Kurt Russell",
	"Jake Gyllenhaal",
	"Ryan Gosling",
	"Colin Firth",
	"Jamie Foxx",
	"Adrien Brody",
	"Roberto Benigni",
	"Jeremy Irons",
	"F. Murray Abraham",
	"Richard Dreyfuss",
	"Peter Finch",
	"Art Carney",
	"Cliff Robertson",
	"Lee Marvin",
	"Rex Harrison",
	"Anthony Quinn",
	"Maximilian Schell",
	"Tom Hardy",
	"David Niven",
	"William Hurt",
	"Yul Brynner",
	"Ernest Borgnine",
	"Benedict Cumberbatch",
	"Rod Steiger",
	"Chloë Grace Moretz",
	"Anna Kendrick",
	"Emily Watson",
	"Helena Bonham Carter",
	"Keira Knightley",
	"Alexis Thorpe",
	"Marion Davies",
	"Scarlett Johansson",
	"Dakota Fanning",
	"Jennifer Aniston",
	"Jennifer Connelly",
	"Rachel McAdams",
	"Carey Mulligan",
	"Mila Kunis",
	"Amanda Seyfried",
	"Jennifer Lopez",
	"Neve Campbell",
	"Fairuza Balk",
	"Jessica Alba",
	"Kristen Stewart",
	"Julie Walters",
	"Rooney Mara",
	"Jamie Lee Curtis",
	"Emma Stone",
	"Kirsten Dunst",
	"José Ferrer",
	"Broderick Crawford",
	"Ronald Colman",
	"Fredric March",
	"Ray Milland",
	"Bing Crosby",
	"Paul Lukas",
	"Robert Donat",
	"Paul Muni",
	"Victor McLaglen",
	"Charles Laughton",
	"Wallace Beery",
	"Lionel Barrymore",
	"Jeff Goldblum",
	"Chris Hemsworth",
	"Warner Baxter",
	"Emil Jannings",
	"Chris Cooper",
	"Jim Broadbent",
	"James Coburn",
	"Cuba Gooding Jr.",
	"Martin Landau",
	"Jack Palance",
	"Kevin Kline",
	"Don Ameche",
	"Kate Beckinsale",
	"Zooey Deschanel",
	"Michelle Williams",
	"Milla Jovovich",
	"Selena Gomez",
	"Rachel Weisz",
	"Kristen Bell",
	"Katherine Heigl",
	"Liv Tyler",
	"Jessica Chastain",
	"Megan Fox",
	"Betty White",
	"Geraldine Page",
	"Eliza Dushku",
	"Robin Wright",
	"Leighton Meester",
	"Jennifer Jones",
	"Shirley Temple",
	"Julia Louis-Dreyfus",
	"Olivia Thirlby",
	"Cher",
	"Sissy Spacek",
	"Louise Fletcher",
	"Julie Christie",
	"Patricia Neal",
	"Haing S. Ngor",
	"Louis Gossett Jr.",
	"John Gielgud",
	"Timothy Hutton",
	"Melvyn Douglas",
	"Jason Robards",
	"George Burns",
	"Christian Bale",
	"Ethan Hawke",
	"Ben Johnson",
	"John Mills",
	"Jack Albertson",
	"Sean Penn",
	"George Kennedy",
	"Walter Matthau",
	"Martin Balsam",
	"Peter Ustinov",
	"Ed Begley",
	"George Chakiris",
	"Hugh Griffith",
	"Burl Ives",
	"Red Buttons",
	"Edmond O'Brien",
	"Chris Pratt",
	"Frank Sinatra",
	"Anne Bancroft",
	"Kim Novak",
	"Simone Signoret",
	"Elliot Page",
	"Angela Lansbury",
	"Judy Holliday",
	"Loretta Young",
	"Shirley Jones",
	"Vera Farmiga",
	"Helen Hayes",
	"Marie Dressler",
	"Janet Gaynor",
	"Lupita Nyong'o",
	"Octavia Spencer",
	"Melissa Leo",
	"Mo'Nique",
	"Marlee Matlin",
	"Tilda Swinton",
	"Jennifer Hudson",
	"Renée Zellweger",
	"Marcia Gay Harden",
	"Anna Paquin",
	"Marisa Tomei",
	"Mercedes Ruehl",
	"Brenda Fricker",
	"Jean Reno",
	"George Sanders",
	"Dean Jagger",
	"Walter Huston",
	"Edmund Gwenn",
	"Harold Russell",
	"Hugh Grant",
	"Barry Fitzgerald",
	"Charles Coburn",
	"Van Heflin",
	"Donald Crisp",
	"Thomas Mitchell",
	"Walter Brennan",
	"Joseph Schildkraut",
	"Keanu Reeves",
	"Channing Tatum",
	"Hugh Jackman",
	"Dwayne Johnson",
	"Adam Sandler",
	"Daniel Radcliffe",
	"Daniel Craig",
	"Henry Cavill",
	"Vin Diesel",
	"Ben Affleck",
	"Chris Pine",
	"Olympia Dukakis",
	"Peggy Ashcroft",
	"Linda Hunt",
	"Maureen Stapleton",
	"Mary Steenburgen",
	"Beatrice Straight",
	"Vanessa Redgrave",
	"Lee Grant",
	"Eileen Heckart",
	"Cloris Leachman",
	"Ruth Gordon",
	"Estelle Parsons",
	"Sandy Dennis",
	"Shelley Winters",
	"Maggie Gyllenhaal",
	"Katie Holmes",
	"Patty Duke",
	"Rita Moreno",
	"Wendy Hiller",
	"Miyoshi Umeki",
	"Dorothy Malone",
	"Jo Van Fleet",
	"Eva Marie Saint",
	"Gloria Grahame",
	"Kim Hunter",
	"Lee J. Cobb",
	"Andrew Garfield",
	"John Cazale",
	"Jeremy Renner",
	"Steve Carell",
	"Jean Dujardin",
	"Chris Evans",
	"James Franco",
	"Zach Galifianakis",
	"Will Ferrell",
	"Shia LaBeouf",
	"Seth Rogen",
	"Joseph Gordon-Levitt",
	"Ryan Reynolds",
	"Paul Rudd",
	"Jason Segel",
	"Jason Statham",
	"Dick Van Dyke",
	"Jesse Eisenberg",
	"Owen Wilson",
	"Jason Bateman",
	"Tyler Perry",
	"Liam Hemsworth",
	"William Shatner",
	"Gene Wilder",
	"Thora Birch",
	"Claire Trevor",
	"Celeste Holm",
	"Anne Baxter",
	"Queen Latifah",
	"Ethel Barrymore",
	"Rosario Dawson",
	"Teresa Wright",
	"Mary Astor",
	"Jane Darwell",
	"Alicia Vikander",
	"Mia Wasikowska",
	"Abigail Breslin",
	"Gale Sondergaard",
	"Melissa McCarthy",
	"Tina Fey",
	"Zoe Saldana",
	"Elisabeth Moss",
	"Adrianne Palicki",
	"Jennifer Garner",
	"Kristen Wiig",
	"June Squibb",
	"Sally Hawkins",
	"Kaley Cuoco",
	"Naomi Watts",
	"Robert Pattinson",
	"Charlie Hunnam",
	"Nicholas Hoult",
	"Aaron Taylor-Johnson",
	"Bryan Cranston",
	"Gerard Butler",
	"Paul Walker",
	"Karl Urban",
	"Logan Lerman",
	"Dave Franco",
	"Tom Hiddleston",
	"Peter Dinklage",
	"Taylor Kitsch",
	"Edward Norton",
	"Guy Pearce",
	"Mark Ruffalo",
	"Mickey Rourke",
	"Frank Langella",
	"Eddie Redmayne",
	"David Strathairn",
	"Terrence Howard",
	"Ralph Fiennes",
	"Tom Wilkinson",
	"Richard Farnsworth",
	"Nick Nolte",
	"AnnaSophia Robb",
	"Gemma Arterton",
	"Olivia Wilde",
	"Isla Fisher",
	"Shailene Woodley",
	"Rebel Wilson",
	"Emma Roberts",
	"Amber Heard",
	"Teresa Palmer",
	"Saoirse Ronan",
	"Elizabeth Banks",
	"Ida Lupino",
	"Natalie Dormer",
	"Brittany Snow",
	"Kate Mara",
	"Julianne Hough",
	"Lily Collins",
	"Cobie Smulders",
	"Alice Eve",
	"Jamie Chung",
	"Noomi Rapace",
	"Blake Lively",
	"Maggie Grace",
	"Jessica Biel",
	"Eva Green",
	"Peter Fonda",
	"Woody Harrelson",
	"Billy Bob Thornton",
	"Idris Elba",
	"Nigel Hawthorne",
	"Laurence Fishburne",
	"Stephen Rea",
	"Warren Beatty",
	"Richard Harris",
	"John Cusack",
	"Kenneth Branagh",
	"Edward James Olmos",
	"Max von Sydow",
	"Bruce Dern",
	"Bob Hoskins",
	"James Woods",
	"John Hawkes",
	"James Garner",
	"Sam Waterston",
	"Tom Hulce",
	"Albert Finney",
	"Tom Conti",
	"Tom Courtenay",
	"Dudley Moore",
	"John Hurt",
	"Kat Dennings",
	"Priyanka Chopra Jonas",
	"Emmanuelle Riva",
	"Greta Gerwig",
	"Brie Larson",
	"Jessica Lucas",
	"Maria Falconetti",
	"Greer Garson",
	"Rosalind Russell",
	"Raquel Welch",
	"Linda Fiorentino",
	"Gabourey Sidibe",
	"Judy Davis",
	"Mia Farrow",
	"Audrey Tautou",
	"Jeanne Moreau",
	"Jane Wyman",
	"Gena Rowlands",
	"Lesley Manville",
	"Elizabeth Olsen",
	"Nastassja Kinski",
	"Mélanie Laurent",
	"Whitney Houston",
	"Felicity Huffman",
	"Imelda Staunton",
	"Oscar Isaac",
	"Jon Heder",
	"Miles Teller",
	"Daniel Brühl",
	"James Gandolfini",
	"Michael B. Jordan",
	"Anthony Perkins",
	"David Thewlis",
	"Klaus Kinski",
	"Malcolm McDowell",
	"Ray Winstone",
	"Jean-Paul Belmondo",
	"Andy Serkis",
	"Matthew Broderick",
	"Dennis Hopper",
	"Michael Rooker",
	"Vincent Gallo",
	"Kevin Spacey",
	"Vincent Cassel",
	"J.K. Simmons",
	"Boris Karloff",
	"Peter Lorre",
	"Matthew McConaughey",
	"Paddy Considine",
	"Ryan Phillippe",
	"Kerry Washington",
	"Carrie-Anne Moss",
	"Janet Leigh",
	"Catalina Sandino Moreno",
	"Samantha Morton",
	"Keisha Castle-Hughes",
	"Barbara Stanwyck",
	"Joan Allen",
	"Janet McTeer",
	"Fernanda Montenegro",
	"Kristin Scott Thomas",
	"Brenda Blethyn",
	"Elisabeth Shue",
	"Miranda Richardson",
	"Stockard Channing",
	"Luise Rainer",
	"Mary McDonnell",
	"Lucille Ball",
	"Laura Dern",
	"Pauline Collins",
	"Isabelle Adjani",
	"Melanie Griffith",
	"Sally Kirkland",
	"Jane Alexander",
	"Marsha Mason",
	"Freddie Highmore",
	"Michael J. Fox",
	"John Travolta",
	"Chow Yun-Fat",
	"Seth MacFarlane",
	"Jet Li",
	"John Houseman",
	"Chuck Norris",
	"Jean-Claude Van Damme",
	"Sam Rockwell",
	"Takashi Shimura",
	"Richard E. Grant",
	"Leslie Nielsen",
	"Simon Pegg",
	"John Malkovich",
	"Michael Shannon",
	"Martin Sheen",
	"Christopher Guest",
	"Alan Rickman",
	"Jackie Earle Haley",
	"Gig Young",
	"James Spader",
	"Eric Bana",
	"Romain Duris",
	"Robert Shaw",
	"Jacki Weaver",
	"Bérénice Bejo",
	"Hailee Steinfeld",
	"Jennifer Jason Leigh",
	"Kathleen Quinlan",
	"Taraji P. Henson",
	"Amy Ryan",
	"Ruby Dee",
	"Jill Clayburgh",
	"Adriana Barraza",
	"Rinko Kikuchi",
	"Catherine Keener",
	"Charlotte Rampling",
	"Sophie Okonedo",
	"Patricia Clarkson",
	"Shohreh Aghdashloo",
	"Lindsay Lohan",
	"Michelle Trachtenberg",
	"Chloë Sevigny",
	"Lynn Redgrave",
	"Rachel Griffiths",
	"Margot Robbie",
	"Lili Taylor",
	"Robin Weigert",
	"Lake Bell",
	"Claude Rains",
	"Steve Buscemi",
	"John Rhys-Davies",
	"Jean-Louis Trintignant",
	"Joseph Cotten",
	"Barry Pepper",
	"Erich von Stroheim",
	"Patrick Wilson",
	"Christopher Lloyd",
	"Ben Foster",
	"Joel McCrea",
	"Choi Min-sik",
	"Ewan McGregor",
	"Gael García Bernal",
	"Bruno Ganz",
	"Sean Astin",
	"Irrfan Khan",
	"Michael C. Hall",
	"Roy Scheider",
	"Casey Affleck",
	"Gary Busey",
	"Norman Reedus",
	"Jeff Daniels",
	"Stanley Tucci",
	"Kiefer Sutherland",
	"Michelle Yeoh",
	"Léa Seydoux",
	"Dakota Johnson",
	"Julie Delpy",
	"Linda Hamilton",
	"Carrie Fisher",
	"Pam Grier",
	"Björk",
	"Emily Browning",
	"Juliette Lewis",
	"Sarah Jessica Parker",
	"Piper Laurie",
	"Miley Cyrus",
	"Lily Tomlin",
	"Jane Seymour",
	"Gloria Stuart",
	"Talia Shire",
	"Gal Gadot",
	"Sue Lyon",
	"Olivia Newton-John",
	"Minnie Driver",
	"Teri Garr",
	"Keri Russell",
	"Jean Seberg",
	"Sarah Polley",
	"Josh Brolin",
	"Hal Holbrook",
	"Djimon Hounsou",
	"Matt Dillon",
	"Alan Alda",
	"Thomas Haden Church",
	"Clive Owen",
	"Ken Watanabe",
	"Suraj Sharma",
	"John C. Reilly",
	"Michael Clarke Duncan",
	"Haley Joel Osment",
	"Greg Kinnear",
	"Burt Reynolds",
	"Robert Forster",
	"Jason Schwartzman",
	"William H. Macy",
	"Armin Mueller-Stahl",
	"Tim Roth",
	"James Cromwell",
	"Chazz Palminteri",
	"Gary Sinise",
	"Paul Scofield",
	"Pete Postlethwaite",
	"Hugo Weaving",
	"Jada Pinkett Smith",
	"Tatum O'Neal",
	"Anna Faris",
	"Hattie McDaniel",
	"Famke Janssen",
	"Rosamund Pike",
	"Bonnie Hunt",
	"Leslie Mann",
	"Mindy Kaling",
	"Thandiwe Newton",
	"Amy Poehler",
	"Amanda Peet",
	"Julia Stiles",
	"Maria Bello",
	"Eva Mendes",
	"Emily Blunt",
	"Rose Byrne",
	"Ashley Judd",
	"Emilia Clarke",
	"Christina Applegate",
	"Nia Long",
	"Felicity Jones",
	"Téa Leoni",
	"Alexandra Daddario",
	"Jena Malone",
	"Richard Gere",
	"Nick Frost",
	"Ray Liotta",
	"Chris Rock",
	"Jon Hamm",
	"Neil Patrick Harris",
	"Charlie Sheen",
	"Mark Rylance",
	"Andy Garcia",
	"Michael Lerner",
	"Graham Greene",
	"Bruce Davison",
	"Dan Aykroyd",
	"Danny Aiello",
	"River Phoenix",
	"Dean Stockwell",
	"Billy Crystal",
	"John Goodman",
	"Orlando Bloom",
	"Stellan Skarsgård",
	"Alexander Skarsgård",
	"Mike Myers",
	"Tyrese Gibson",
	"Elijah Wood",
	"Danny DeVito",
	"Susan Hayward",
	"Michelle Rodriguez",
	"Sarah Michelle Gellar",
	"Sandra Oh",
	"Margot Kidder",
	"Beyoncé",
	"Rebecca Hall",
	"Piper Perabo",
	"Courteney Cox",
	"Parker Posey",
	"Paula Patton",
	"Michelle Monaghan",
	"Claire Danes",
	"Allison Janney",
	"Kate Bosworth",
	"Evan Rachel Wood",
	"Mira Sorvino",
	"Ziyi Zhang",
	"Amanda Bynes",
	"Lisa Kudrow",
	"Brit Marling",
	"Cynthia Erivo",
	"Sofía Vergara",
	"Mandy Moore",
	"Virginia Madsen",
	"James Marsden",
	"Tim Allen",
	"Giovanni Ribisi",
	"Rutger Hauer",
	"Vince Vaughn",
	"Brian Cox",
	"Dennis Quaid",
	"John Leguizamo",
	"Michael Keaton",
	"Billy Burke",
	"Brendan Gleeson",
	"Charles Bronson",
	"Jonathan Pryce",
	"Tobey Maguire",
	"Michael Sheen",
	"Justin Long",
	"Jack Black",
	"Mel Brooks",
	"Pierce Brosnan",
	"Sean Bean",
	"Mahershala Ali",
	"Josh Duhamel",
	"Eddie Murphy",
	"Jon Favreau",
	"Danny Glover",
	"Freida Pinto",
	"Hilary Duff",
	"Mary Elizabeth Winstead",
	"Jennifer Coolidge",
	"Andrea Riseborough",
	"Molly Ringwald",
	"January Jones",
	"Maya Rudolph",
	"Sophie Marceau",
	"Franka Potente",
	"Claire Foy",
	"Rashida Jones",
	"Alicia Silverstone",
	"Lillian Gish",
	"Evangeline Lilly",
	"Olivia Colman",
	"Mireille Enos",
	"Jennifer Love Hewitt",
	"Emmy Rossum",
	"Joey King",
	"Ginnifer Goodwin",
	"Christine Taylor",
	"Vanessa Hudgens",
	"Abbie Cornish",
	"Florence Pugh",
	"Ian Holm",
	"Nathan Lane",
	"Cary Elwes",
	"Martin Lawrence",
	"Steve Coogan",
	"Sacha Baron Cohen",
	"Jeffrey Wright",
	"Jackie Chan",
	"Aaron Eckhart",
	"Sam Worthington",
	"Jack Davenport",
	"Alfred Molina",
	"Tim Curry",
	"Mark Hamill",
	"Brendan Fraser",
	"Ice Cube",
	"Liev Schreiber",
	"Ed Helms",
	"Val Kilmer",
	"Russell Brand",
	"Craig T. Nelson",
	"Bernie Mac",
	"Patrick Stewart",
	"Seth Green",
	"Ashton Kutcher",
	"Randy Quaid",
	"Wesley Snipes",
	"David Oyelowo",
	"Mark Strong",
	"Rob Schneider",
	"Jay Baruchel",
	"Hayden Christensen",
	"Ray Stevenson",
	"Paul Bettany",
	"Hugh Laurie",
	"Chris Tucker",
	"John Candy",
	"Richard Attenborough",
	"Chris O'Donnell",
	"Benjamin Bratt",
	"Common",
	"Marlon Wayans",
	"Albert Brooks",
	"Aaron Paul",
	"Macaulay Culkin",
	"Sam Elliott",
	"Taron Egerton",
	"Jim Caviezel",
	"Elvis Presley",
	"Jonah Hill",
	"Sung Kang",
	"Jason Sudeikis",
	"Josh Hartnett",
	"Cillian Murphy",
	"Billy Crudup",
	"Anthony Mackie",
	"John Barrymore",
	"Timothy Olyphant",
	"Josh Gad",
	"Billy Zane",
	"Luke Wilson",
	"Peter Sarsgaard",
	"Rhys Ifans",
	"Topher Grace",
	"Kevin Hart",
	"Paul Dano",
	"Bill Hader",
	"Rob Lowe",
	"Mel Blanc",
	"David Spade",
	"Rob Riggle",
	"Lance Henriksen",
	"Richard Jenkins",
	"Emilio Estevez",
	"Michael Ealy",
	"Jamie Bell",
	"Troy Baker",
	"Danny McBride",
	"Jonathan Rhys Meyers",
	"Michael Cera",
	"Bill Paxton",
	"Ioan Gruffudd",
	"Andrew Lincoln",
	"Ezra Miller",
	"Bill Pullman",
	"Craig Robinson",
	"Charlie Day",
	"Andy Samberg",
	"Garrett Hedlund",
	"Cam Gigandet",
	"John Krasinski",
	"Kevin James",
	"Christopher Reeve",
	"James McAvoy",
	"Rufus Sewell",
	"Adam Driver",
	"Ned Beatty",
	"John Cleese",
	"John Turturro",
	"Jerry Lewis",
];
const defaultDirectors = [
	"Steven Spielberg",
	"Christopher Nolan",
	"Martin Scorsese",
	"Quentin Tarantino",
	"David Fincher",
	"Stanley Kubrick",
	"Robert Zemeckis",
	"Clint Eastwood",
	"Ridley Scott",
	"Francis Ford Coppola",
	"Joel Coen",
	"James Cameron",
	"Alfred Hitchcock",
	"Frank Darabont",
	"Tim Burton",
	"Sam Mendes",
	"Woody Allen",
	"Steven Soderbergh",
	"Tony Scott",
	"Darren Aronofsky",
	"Danny Boyle",
	"Ron Howard",
	"Irvin Kershner",
	"Roman Polanski",
	"Mel Gibson",
	"Alejandro G. Iñárritu",
	"Guy Ritchie",
	"Lilly Wachowski",
	"Lana Wachowski",
	"Milos Forman",
	"Sergio Leone",
	"Ethan Coen",
	"Chris Columbus",
	"Luc Besson",
	"Michael Mann",
	"Peter Weir",
	"Wes Anderson",
	"Oliver Stone",
	"Jonathan Demme",
	"Gore Verbinski",
	"Denis Villeneuve",
	"Alfonso Cuarón",
	"M. Night Shyamalan",
	"Rob Reiner",
	"Ang Lee",
	"Sidney Lumet",
	"Billy Wilder",
	"Todd Phillips",
	"Damien Chazelle",
	"Jason Reitman",
	"Morten Tyldum",
	"Tony Kaye",
	"James Mangold",
	"David Lynch",
	"Paul Thomas Anderson",
	"Brian De Palma",
	"Spike Jonze",
	"George Lucas",
	"Peter Jackson",
	"Baz Luhrmann",
	"Akira Kurosawa",
	"Evan Goldberg",
	"Barry Levinson",
	"John Lasseter",
	"Gus Van Sant",
	"Terry Gilliam",
	"Fernando Meirelles",
	"Shane Black",
	"James McTeigue",
	"Michael Bay",
	"Richard Linklater",
	"Roland Emmerich",
	"Gary Ross",
	"David O. Russell",
	"Michel Gondry",
	"Cameron Crowe",
	"Tom Hooper",
	"Bryan Singer",
	"Ben Affleck",
	"Paul Haggis",
	"Marc Forster",
	"Joe Wright",
	"Mike Nichols",
	"Pedro Almodóvar",
	"Tom Tykwer",
	"Spike Lee",
	"Terry Jones",
	"Jaume Collet-Serra",
	"Brad Bird",
	"Joel Schumacher",
	"Kathryn Bigelow",
	"J.J. Abrams",
	"Andrew Niccol",
	"Mike Newell",
	"Matthew Vaughn",
	"Wolfgang Petersen",
	"Doug Liman",
	"David Cronenberg",
	"Nancy Meyers",
	"Michael Curtiz",
	"Victor Fleming",
	"Martin Campbell",
	"Curtis Hanson",
	"Jim Jarmusch",
	"Orson Welles",
	"Frank Capra",
	"Edward Zwick",
	"Charles Chaplin",
	"Rob Marshall",
	"Richard Kelly",
	"Terry George",
	"Paul Greengrass",
	"Jonathan Levine",
	"Jean-Marc Vallée",
	"Nick Cassavetes",
	"Harold Ramis",
	"Lasse Hallström",
	"Terrence Malick",
	"David Lean",
	"Roger Donaldson",
	"Alexander Payne",
	"Nicolas Winding Refn",
	"Sofia Coppola",
	"Antoine Fuqua",
	"Lars von Trier",
	"Tony Gilroy",
	"John Huston",
	"Ingmar Bergman",
	"Neil Burger",
	"Jay Roach",
	"Alan Parker",
	"Duncan Jones",
	"Howard Hawks",
	"Taylor Hackford",
	"Alejandro Amenábar",
	"William Friedkin",
	"Byron Howard",
	"Rich Moore",
	"Park Chan-wook",
	"Guillermo del Toro",
	"Sydney Pollack",
	"Tom McCarthy",
	"Jan de Bont",
	"Bennett Miller",
	"William Wyler",
	"James Wan",
	"Louis Leterrier",
	"Glenn Ficarra",
	"John Requa",
	"Peter Berg",
	"John Hillcoat",
	"Kevin Smith",
	"Sean Penn",
	"Stephen Daldry",
	"Joss Whedon",
	"Jean-Pierre Jeunet",
	"Anthony Minghella",
	"Valerie Faris",
	"Jonathan Dayton",
	"John G. Avildsen",
	"Ben Stiller",
	"George Roy Hill",
	"Fritz Lang",
	"Paul Verhoeven",
	"Norman Jewison",
	"John Landis",
	"Alex Garland",
	"Eric Bress",
	"J. Mackye Gruber",
	"Roberto Benigni",
	"John Ford",
	"Phillip Noyce",
	"Francis Lawrence",
	"James L. Brooks",
	"Dan Gilroy",
	"Martin McDonagh",
	"Tate Taylor",
	"John Frankenheimer",
	"Yimou Zhang",
	"Jean-Jacques Annaud",
	"Elia Kazan",
	"Kevin Macdonald",
	"Barry Sonnenfeld",
	"George Clooney",
	"Blake Edwards",
	"Giuseppe Tornatore",
	"Michael Cimino",
	"Gavin O'Connor",
	"Baltasar Kormákur",
	"John Madden",
	"Federico Fellini",
	"James Marsh",
	"Steve McQueen",
	"Franklin J. Schaffner",
	"Derek Cianfrance",
	"Krzysztof Kieslowski",
	"Ivan Reitman",
	"Tom Ford",
	"Theodore Melfi",
	"Brad Anderson",
	"Michael Moore",
	"Kar-Wai Wong",
	"J.A. Bayona",
	"Kenneth Lonergan",
	"Oliver Hirschbiegel",
	"Stephen Frears",
	"Nora Ephron",
	"Barry Jenkins",
	"Robert Wise",
	"Michael Haneke",
	"Florian Henckel von Donnersmarck",
	"Robert Redford",
	"Lee Tamahori",
	"Mel Brooks",
	"Stanley Donen",
	"John Sturges",
	"Gabriele Muccino",
	"Guy Hamilton",
	"Robert Mulligan",
	"Richard Attenborough",
	"François Truffaut",
	"Mark Romanek",
	"Jim Sheridan",
	"Brad Silberling",
	"Robert Altman",
	"Daniel Espinosa",
	"Don Siegel",
	"Kevin Costner",
	"Terence Young",
	"Martin Brest",
	"George Cukor",
	"Allen Hughes",
	"Joseph L. Mankiewicz",
	"Richard Schenkman",
	"John Lee Hancock",
	"Pierre Morel",
	"J.C. Chandor",
	"Sam Peckinpah",
	"Joe Carnahan",
	"Garry Marshall",
	"Tomas Alfredson",
	"Hal Ashby",
	"Jacques Audiard",
	"Jon Avnet",
	"Bernardo Bertolucci",
	"John McTiernan",
	"John Dahl",
	"Andrew Davis",
	"Robert Stromberg",
	"Fred Zinnemann",
	"Adrian Lyne",
	"Luis Buñuel",
	"Peyton Reed",
	"David Dobkin",
	"Mike Leigh",
	"Carol Reed",
	"Asghar Farhadi",
	"Werner Herzog",
	"Lone Scherfig",
	"Adam McKay",
	"Ruben Fleischer",
	"Roger Michell",
	"Richard Donner",
	"Julie Taymor",
	"Jessie Nelson",
	"Frank Oz",
	"Gene Kelly",
	"Iain Softley",
	"Walter Hill",
	"Michael Apted",
	"John Carney",
	"Jerry Zucker",
	"Roger Spottiswoode",
	"Ted Demme",
	"Hayao Miyazaki",
	"Mathieu Kassovitz",
	"Bong Joon Ho",
	"Jaco Van Dormael",
	"Shane Meadows",
	"Paul Weitz",
	"Emir Kusturica",
	"Thomas Vinterberg",
	"Phyllida Lloyd",
	"Olivier Nakache",
	"Éric Toledano",
	"Lewis Gilbert",
	"Garth Davis",
	"Wim Wenders",
	"John Glen",
	"John Schlesinger",
	"Jeff Nichols",
	"Michel Hazanavicius",
	"F. Gary Gray",
	"David Frankel",
	"Peter Segal",
	"Sylvester Stallone",
	"Niels Arden Oplev",
	"Stanley Kramer",
	"Gary Fleder",
	"Todd Haynes",
	"Corey Yuen",
	"Anne Fletcher",
	"Otto Preminger",
	"Lee Daniels",
	"James Gray",
	"Andrew Lau",
	"Alan Mak",
	"Chuck Russell",
	"Anton Corbijn",
	"Lenny Abrahamson",
	"David R. Ellis",
	"George Miller",
	"Todd Field",
	"Arthur Penn",
	"Vittorio De Sica",
	"Walter Salles",
	"F.W. Murnau",
	"Ken Loach",
	"Aamir Khan",
	"Wolfgang Reitherman",
	"Stuart Rosenberg",
	"Paolo Sorrentino",
	"Kim Ki-duk",
	"Craig Gillespie",
	"Terry Zwigoff",
	"Sharon Maguire",
	"Richard Eyre",
	"George A. Romero",
	"Jean-Luc Godard",
	"Alan J. Pakula",
	"François Ozon",
	"Paul Feig",
	"Noah Baumbach",
	"Chris Weitz",
	"Randal Kleiser",
	"Scott Derrickson",
	"Scott Cooper",
	"Lukas Moodysson",
	"Buster Keaton",
	"George Stevens",
	"Bruce Beresford",
	"Robert Benton",
	"Jon Favreau",
	"James Ivory",
	"Peter Cattaneo",
	"Robert Luketic",
	"Andrei Tarkovsky",
	"John Boorman",
	"Susanne Bier",
	"Michael Powell",
	"Jon Amiel",
	"Fatih Akin",
	"George P. Cosmatos",
	"Richard Fleischer",
	"Andrew Dominik",
	"Wolfgang Becker",
	"Michael Winterbottom",
	"Paco Plaza",
	"Jaume Balagueró",
	"James Whale",
	"Robert Rodriguez",
	"Richard LaGravenese",
	"Jon Turteltaub",
	"Gregory Hoblit",
	"Robert Schwentke",
	"Bobcat Goldthwait",
	"Robert Stevenson",
	"Mark Herman",
	"Leo McCarey",
	"Richard Curtis",
	"Stephen Gaghan",
	"Henry Hathaway",
	"Nuri Bilge Ceylan",
	"Daniel Barber",
	"Chris Noonan",
	"Jane Campion",
	"Kimberly Peirce",
	"Vincente Minnelli",
	"Sergei Eisenstein",
	"Nicholas Ray",
	"John Patrick Shanley",
	"Lewis Milestone",
	"Lisa Cholodenko",
	"John Badham",
	"Julian Schnabel",
	"Charles Crichton",
	"Neil Jordan",
	"Andrea Arnold",
	"Banksy",
	"Shane Carruth",
	"Ernst Lubitsch",
	"Raoul Walsh",
	"John Curran",
	"Olivier Assayas",
	"Morgan Spurlock",
	"Yasujirô Ozu",
	"Adam Brooks",
	"Xavier Dolan",
	"Abdellatif Kechiche",
	"Richard Brooks",
	"John Wells",
	"Gurinder Chadha",
	"Louis Malle",
	"Herbert Ross",
	"Mike Figgis",
	"Simon Curtis",
	"Philip Kaufman",
	"Patty Jenkins",
	"Daniel Alfredson",
	"Henri-Georges Clouzot",
	"Denzel Washington",
	"Mike Binder",
	"Juan José Campanella",
	"George Tillman Jr.",
	"Steven Knight",
	"Aki Kaurismäki",
	"Peter Bogdanovich",
	"Takashi Miike",
	"David Hand",
	"Roland Joffé",
	"Debra Granik",
	"Peter Webber",
	"Robert Aldrich",
	"Peter Yates",
	"Gregor Jordan",
	"Kirsten Sheridan",
	"Damián Szifron",
	"Ava DuVernay",
	"Jean-Pierre Dardenne",
	"Luc Dardenne",
	"Vadim Perelman",
	"James Foley",
	"Allen Coulter",
	"Jean Renoir",
	"Tim Robbins",
	"Jules Dassin",
	"Joseph Gordon-Levitt",
	"Bill Condon",
	"Emeric Pressburger",
	"Abbas Kiarostami",
	"Michelangelo Antonioni",
	"Gillo Pontecorvo",
	"Scott Derrickson",
	"William A. Wellman",
	"Luchino Visconti",
	"Gavin Hood",
	"Mark Waters",
	"Robert De Niro",
	"Cary Joji Fukunaga",
	"Kenneth Branagh",
	"John Hughes",
	"Atom Egoyan",
	"Lawrence Kasdan",
	"Tarsem Singh",
	"Christophe Gans",
	"Mervyn LeRoy",
	"Henry Koster",
	"Martin Ritt",
	"Niki Caro",
	"Hirokazu Koreeda",
	"Henry Alex Rubin",
	"Daniel Monzón",
	"John Maybury",
	"Carl Theodor Dreyer",
	"Penny Marshall",
	"Justin Kurzel",
	"John Hamburg",
	"Grant Heslov",
	"Russell Mulcahy",
	"Gary Winick",
	"Jonathan Glazer",
	"Peter Greenaway",
	"Bob Fosse",
	"Charles Laughton",
	"Jim Sharman",
	"Mikael Håfström",
	"Justin Chadwick",
	"Pablo Larraín",
	"Robert Rossen",
	"Ernest B. Schoedsack",
	"Anthony Mann",
	"Richard Lester",
	"Cecil B. DeMille",
	"Julio Medem",
	"Rowan Joffe",
	"Sam Wood",
	"John Michael McDonagh",
	"Malik Bendjelloul",
	"Karyn Kusama",
	"Alexander Mackendrick",
	"Marjane Satrapi",
	"Vincent Paronnaud",
	"Bille August",
	"J. Lee Thompson",
	"Mick Jackson",
	"Benh Zeitlin",
	"Vincent Ward",
	"George Seaton",
	"Costa-Gavras",
	"Mark Tonderai",
	"Isabel Coixet",
	"Scott Hicks",
	"P.J. Hogan",
	"Ronald Neame",
	"Jacques Tourneur",
	"Merian C. Cooper",
	"John Milius",
	"Asif Kapadia",
	"Peter Hyams",
	"Jerome Robbins",
	"Mimi Leder",
	"Robert Bresson",
	"Ron Underwood",
	"John Cassavetes",
	"Lynne Ramsay",
	"Gaspar Noé",
	"Clyde Bruckman",
	"Ben Lewin",
	"Olivier Dahan",
	"Jim Henson",
	"Robert Wiene",
	"Michael Radford",
	"Jeremiah S. Chechik",
	"Jee-woon Kim",
	"Michael Cristofer",
	"John Guillermin",
	"Ryan Fleck",
	"Floria Sigismondi",
	"Ted Post",
	"Volker Schlöndorff",
	"Barbet Schroeder",
	"Clyde Geronimi",
	"Florian Gallenberger",
	"Eric Goldberg",
	"Roy Andersson",
	"Danny DeVito",
	"Danis Tanovic",
	"John McNaughton",
	"Nikita Mikhalkov",
	"Joachim Rønning",
	"Espen Sandberg",
	"Cristian Mungiu",
	"Nicole Holofcener",
	"Preston Sturges",
	"Bob Rafelson",
	"Gillian Armstrong",
	"Nicholas Hytner",
	"Claude Berri",
	"Ari Folman",
	"Saul Dibb",
	"Nick Murphy",
	"Dennis Hopper",
	"Andrzej Wajda",
	"Rainer Werner Fassbinder",
	"Satyajit Ray",
	"Jean-Pierre Melville",
	"Christine Jeffs",
	"Agnieszka Holland",
	"Majid Majidi",
	"Alain Resnais",
	"Peter Collinson",
	"Peter Chelsom",
	"Dennis Gansel",
	"Liev Schreiber",
	"Nigel Cole",
	"William Keighley",
	"Uli Edel",
	"Oren Moverman",
	"Ken Annakin",
	"Nicholas Jarecki",
	"Arthur Hiller",
	"Laura Poitras",
	"Emile Ardolino",
	"Tony Goldwyn",
	"Henry King",
	"Tobe Hooper",
	"Ryan Murphy",
	"Josef von Sternberg",
	"Claude Chabrol",
	"Nicolas Roeg",
	"Kenji Mizoguchi",
	"Luis Mandoki",
	"Franco Zeffirelli",
	"István Szabó",
	"Joby Harold",
	"Mark Rydell",
	"Emilio Estevez",
	"Jacques Tati",
	"Brian Levant",
	"Peter Medak",
	"Jonas Åkerlund",
	"Edmund Goulding",
	"Michael Hoffman",
	"David Zucker",
	"Charlie Kaufman",
	"Mira Nair",
	"Jodie Foster",
	"D.W. Griffith",
	"Harold Becker",
	"Vincent Gallo",
	"Gene Saks",
	"Dominic Sena",
	"John Luessenhop",
	"Robert Siodmak",
	"Jamie Uys",
	"Christophe Barratier",
	"Ken Russell",
	"Mike Mills",
	"John Cameron Mitchell",
	"Tom Dey",
	"Andrey Zvyagintsev",
	"Tetsuya Nakashima",
	"Roberto Rossellini",
	"Wayne Wang",
	"William Dieterle",
	"Sarah Polley",
	"Peter Faiman",
	"Andrew Marton",
	"Timo Vuorensola",
	"Edward Dmytryk",
	"Lindsay Anderson",
	"Leonid Gaidai",
	"Delmer Daves",
	"Marc Caro",
	"Éric Rohmer",
	"Yorgos Lanthimos",
	"Norman Z. McLeod",
	"Warren Beatty",
	"Hugh Hudson",
	"Marcel Carné",
	"Jean-François Richet",
	"Kenny Ortega",
	"King Vidor",
	"Andrew V. McLaglen",
	"Michael Winner",
	"Patrice Leconte",
	"Jack Clayton",
	"Max Ophüls",
	"Douglas Sirk",
	"John Carpenter",
	"Cy Endfield",
	"Richard Ayoade",
	"Nanni Moretti",
	"Ettore Scola",
	"Radu Mihaileanu",
	"Pascal Laugier",
	"Christopher Morris",
	"Dan Fogelman",
	"Joshua Marston",
	"Guillaume Canet",
	"Barbra Streisand",
	"Frank Marshall",
	"Yôjirô Takita",
	"Fred Schepisi",
	"Tobias Lindholm",
	"George Sluizer",
	"Gary Trousdale",
	"Joachim Trier",
	"Mark Sandrich",
	"Shekhar Kapur",
	"Takeshi Kitano",
	"Errol Morris",
	"Bryan Forbes",
	"Julie Delpy",
	"Charles Shyer",
	"Tamara Jenkins",
	"Ben Younger",
	"Philipp Stölzl",
	"Wash Westmoreland",
	"Richard Glatzer",
	"Karan Johar",
	"Jacques Demy",
	"Tanya Wexler",
	"Jonathan Kaplan",
	"Walter Lang",
	"Hossein Amini",
	"Anatole Litvak",
	"Tod Browning",
	"Justin Zackham",
	"Elem Klimov",
	"Rodrigo García",
	"Robert Hamer",
	"Masaki Kobayashi",
	"Clarence Brown",
	"Deepa Mehta",
	"James Fargo",
	"Samuel Fuller",
	"Joseph Vilsmaier",
	"Jafar Panahi",
	"Anne Fontaine",
	"Neil Armfield",
	"J Blakeson",
	"Ken Hughes",
	"Andrey Konchalovskiy",
	"Michael Crichton",
	"Angelina Jolie",
	"Rouben Mamoulian",
	"Miranda July",
	"Gary Sinise",
	"John Maclean",
	"Jeannot Szwarc",
	"Laurent Cantet",
	"Ian MacNaughton",
	"Mark Robson",
	"Heitor Dhalia",
	"Yôji Yamada",
	"Massy Tadjedin",
	"W.S. Van Dyke",
	"Rob Epstein",
	"Jeffrey Friedman",
	"Richard Starzak",
	"Pier Paolo Pasolini",
	"Donald Petrie",
	"Ashutosh Gowariker",
	"Rod Lurie",
	"Betty Thomas",
	"Fred C. Newmeyer",
	"Julian Gilbey",
	"Anders Thomas Jensen",
	"Gérard Oury",
	"Anthony Harvey",
	"Delbert Mann",
	"Eran Creevy",
	"Tom Stoppard",
	"Larysa Kondracki",
	"Paul McGuigan",
	"David Schwimmer",
	"Richard Benjamin",
	"Audrey Wells",
	"Kaige Chen",
	"Richard Loncraine",
	"James Bridges",
	"Hans Weingartner",
	"Henry Bean",
	"Denys Arcand",
	"Jordan Scott",
	"Clark Johnson",
	"Steve Antin",
	"Charles Vidor",
	"Stefan Ruzowitzky",
	"Tommy Lee Jones",
	"John Lounsbery",
	"Matteo Garrone",
	"Steve Kloves",
	"Robin Hardy",
	"Sebastian Schipper",
	"Joe Dante",
	"Christian Alvart",
	"Hans-Christian Schmid",
	"Moustapha Akkad",
	"Jean-Paul Rappeneau",
	"Peter Mullan",
	"Agnès Varda",
	"Sarah Gavron",
	"Edward Yang",
	"David Lowery",
	"Andy Tennant",
	"Sean Durkin",
	"Michael Patrick King",
	"René Laloux",
	"Marc Rothemund",
	"Jean Negulesco",
	"Frank Borzage",
	"Hany Abu-Assad",
	"Hugh Wilson",
	"Christian Petzold",
	"Gilles Paquet-Brenner",
	"Carl Reiner",
	"Kirk Jones",
	"Sam Taylor",
	"Paul Schrader",
	"Hal Needham",
	"Frank Lloyd",
	"Bill Forsyth",
	"Andrew Jarecki",
	"Susan Seidelman",
	"Mitchell Leisen",
	"Alejandro Jodorowsky",
	"Ruben Östlund",
	"Steve Martino",
	"Charles Walters",
	"Bahman Ghobadi",
	"Jonathan Mostow",
	"Jean Cocteau",
	"Hector Babenco",
	"Jan Sverák",
	"Ramesh Sippy",
	"Jim Mickle",
	"Patrice Chéreau",
	"Leonard Nimoy",
	"Karel Reisz",
	"Ulrich Seidl",
	"Laurence Olivier",
	"Tony Richardson",
	"Stephen Hopkins",
	"Courtney Hunt",
	"Andrzej Zulawski",
	"Michaël R. Roskam",
	"Sacha Gervasi",
	"Michael Brandt",
	"Theodoros Angelopoulos",
	"Archie Mayo",
	"Kaneto Shindô",
	"Ilmar Raag",
	"Joseph Sargent",
	"Steve Gordon",
	"Abderrahmane Sissako",
	"Ritesh Batra",
	"Philippe Claudel",
	"Sidney J. Furie",
	"Albert Lamorisse",
	"Joseph H. Lewis",
	"James Clavell",
	"Philippe Falardeau",
	"Lajos Koltai",
	"Erik Skjoldbjærg",
	"Richard C. Sarafian",
	"Michael Anderson",
	"Karl Freund",
	"Richard J. Lewis",
	"Neil LaBute",
	"James Vanderbilt",
	"Karen Moncrieff",
	"John Cromwell",
	"Sam Taylor-Johnson",
	"Rupert Wyatt",
	"Sönke Wortmann",
	"James Frawley",
	"Simon Wincer",
	"Mikhail Kalatozov",
	"Kristian Levring",
	"Lasse Spang Olsen",
	"Jacques Becker",
	"Ralph Nelson",
	"Gustavo Taretto",
	"Tay Garnett",
	"Caroline Link",
	"Rupert Julian",
	"Martin Rosen",
	"Jerry Zaks",
	"Mario Monicelli",
	"Frank Perry",
	"Richard Thorpe",
	"Bill Pohlad",
	"Nagisa Ôshima",
	"Carlos Saura",
	"Colin Higgins",
	"Randa Haines",
	"Mark Steven Johnson",
	"Martin Zandvliet",
	"Deniz Gamze Ergüven",
	"Erik Poppe",
	"Jûzô Itami",
	"Joel Hopkins",
	"Michael Grandage",
	"Jean Becker",
	"Kevin Spacey",
	"Mabrouk El Mechri",
	"Joshua Logan",
	"Yves Robert",
	"Mike Hodges",
	"Stephan Elliott",
	"Peter Glenville",
	"Jocelyn Moorhouse",
	"Joseph Losey",
	"Tonino Valerii",
	"Nic Balthazar",
	"Aleksey Balabanov",
	"Burt Kennedy",
	"Enzo Barboni",
	"Imtiaz Ali",
	"George Marshall",
	"Douglas Trumbull",
	"John Cornell",
	"Gordon Douglas",
	"Marco Kreuzpaintner",
	"Mia Hansen-Løve",
	"Ulu Grosbard",
	"Kornél Mundruczó",
	"Georg Wilhelm Pabst",
	"Sergio Corbucci",
	"Jake Scott",
	"Elliot Silverstein",
	"Cristi Puiu",
	"Slobodan Sijan",
	"Petter Næss",
	"René Clément",
	"George Sidney",
	"Roger Vadim",
	"Claude Sautet",
	"Roger Corman",
	"Joshua Oppenheimer",
	"Maren Ade",
	"Michael Caton-Jones",
	"Davis Guggenheim",
	"Peter Brook",
	"Eldar Ryazanov",
	"Sergio Castellitto",
	"Michael Ritchie",
	"Michael Gordon",
	"Jean-Jacques Beineix",
	"Bill Duke",
	"Erick Zonca",
	"Christophe Honoré",
	"Luca Guadagnino",
	"Edward D. Wood Jr.",
	"Jerzy Skolimowski",
	"Aleksandr Sokurov",
	"Erich von Stroheim",
	"Bob Clark",
	"Patrick Stettner",
	"Paul Mazursky",
	"George Pal",
	"Nadine Labaki",
	"Jack Conway",
	"Régis Wargnier",
	"George Waggner",
	"George Hickenlooper",
	"Michael Cacoyannis",
	"Tod Williams",
	"Cate Shortland",
	"Declan Donnellan",
	"Richard Quine",
	"Gregory Nava",
	"George Dunning",
	"Grigoriy Chukhray",
	"Gregory La Cava",
	"Olle Hellbom",
	"Til Schweiger",
	"Fred Niblo",
	"Terence Fisher",
	"Tim Fehlbaum",
	"H.C. Potter",
	"Sion Sono",
	"Sandra Nettelbeck",
	"Matthieu Delaporte",
	"Alexandre de La Patellière",
	"Sergey Bondarchuk",
	"Jirí Menzel",
	"Robert Z. Leonard",
	"Marvin J. Chomsky",
	"Mike van Diem",
	"Fedor Bondarchuk",
	"Gabriele Salvatores",
	"Dagur Kári",
	"Götz Spielmann",
	"Lewis Allen",
	"Jean Girault",
	"Margarethe von Trotta",
	"Alain Corneau",
	"George Sherman",
	"Scott McGehee",
	"David Siegel",
	"Rod Daniel",
	"Ermanno Olmi",
	"Georges Franju",
	"Marleen Gorris",
	"László Nemes",
	"Irving Pichel",
	"Melvin Frank",
	"Jan Troell",
	"Gordon Parks",
	"Leander Haußmann",
	"Mat Whitecross",
	"Dalton Trumbo",
	"Bora Dagtekin",
	"Kay Pollak",
	"Robert Fuest",
	"Geoff Murphy",
	"Hiroshi Teshigahara",
	"Basil Dearden",
	"Daniel Mann",
	"Özcan Alper",
	"Edward Sedgwick",
	"Paulo Morelli",
	"Guillermo Arriaga",
	"Erik Van Looy",
	"Fernando Trueba",
	"Bertrand Tavernier",
	"Zhangke Jia",
	"David Mackenzie",
	"Thomas Jahn",
	"Peter Thorwarth",
	"Peter Hewitt",
	"Malcolm Venville",
	"Éric Lartigau",
	"Milcho Manchevski",
	"Nikolaj Arcel",
	"Pavel Lungin",
	"Brian Gibson",
	"Victor Sjöström",
	"Dziga Vertov",
	"Paolo Virzì",
	"Édouard Molinaro",
	"William A. Seiter",
	"Marc Evans",
	"Val Guest",
	"Claude Lelouch",
	"Daniel Petrie",
	"Darnell Martin",
	"John M. Stahl",
	"John Farrow",
	"Xavier Beauvois",
	"Koen Mortier",
	"George Pollock",
	"Joe Alves",
	"Alfred L. Werker",
	"Alex van Warmerdam",
	"Haifaa Al-Mansour",
	"Henri Verneuil",
	"Norman Taurog",
	"Daniel Sánchez Arévalo",
	"Leos Carax",
	"Yilmaz Güney",
	"Irwin Winkler",
	"Juliusz Machulski",
	"Michael Wadleigh",
	"Charles Jarrott",
	"Georgiy Daneliya",
	"Morgan Neville",
	"Eran Kolirin",
	"Philip Seymour Hoffman",
	"Ralph Fiennes",
	"Silvio Soldini",
	"Thom Eberhardt",
	"James W. Horne",
	"Sherry Hormann",
	"Julien Duvivier",
	"Ole Bornedal",
	"Jim McBride",
	"Anthony Asquith",
	"Edgar G. Ulmer",
	"Laslo Benedek",
	"Toshiya Fujita",
	"Wojciech Has",
	"Tamra Davis",
	"Victor Heerman",
	"Carl Franklin",
	"Víctor Erice",
	"Rose Bosch",
	"Rudolph Maté",
	"Tim Roth",
	"Jean Vigo",
	"Gabriel Axel",
	"Bernhard Wicki",
	"Terry Hughes",
	"David Gordon Green",
	"Ján Kadár",
	"David Miller",
	"Richard Kwietniowski",
	"Elmar Klos",
	"Jan Harlan",
	"Richard Marquand",
	"Rebecca Miller",
	"Oskar Roehler",
	"Dick Powell",
	"Frank Tashlin",
	"Jim Strouse",
	"Josef Fares",
	"Diane English",
	"Pietro Germi",
	"Max Färberböck",
	"Ewan McGregor",
	"Sergei Parajanov",
	"Vladimir Menshov",
	"Robert J. Flaherty",
	"Wes Craven",
	"Jerry London",
	"Charles Reisner",
	"Paul Leni",
	"René Clair",
	"Phil Karlson",
	"Edward F. Cline",
	"John Jeffcoat",
	"Ruba Nadda",
	"Christian Zübert",
	"Chantal Akerman",
	"Alexander Korda",
	"Nicholas Meyer",
	"Bo Widerberg",
	"Dmitriy Vasilev",
	"Norman Panama",
	"Søren Kragh-Jacobsen",
	"Nunnally Johnson",
	"André Téchiné",
	"Grímur Hákonarson",
	"Bruce McDonald",
	"Samuel Maoz",
	"Charles Dance",
	"Srdan Golubovic",
	"Seijun Suzuki",
	"Stan Dragoti",
	"Don Taylor",
	"Philippe Lioret",
	"Cédric Klapisch",
	"Lauren Greenfield",
	"Guillem Morales",
	"Wilfred Jackson",
	"Ted Wilde",
	"Harve Foster",
	"Eran Riklis",
	"Xiaogang Feng",
	"Todd Louiso",
	"Felix Herngren",
	"Henry Levin",
	"Ernst Marischka",
	"Hyun-seung Lee",
	"Andreas Dresen",
	"Tassos Boulmetis",
	"Patricia Birch",
	"Richard Franklin",
	"Ursula Meier",
	"David Gordon Green",
	"Anh Hung Tran",
	"Franc Roddam",
	"Arthur Lubin",
	"Sidney Franklin",
	"Garson Kanin",
	"Jean Eustache",
	"Clive Donner",
	"Sidney Lanfield",
	"Marek Koterski",
	"Marius Holst",
	"Alexander Hall",
	"Ludwig Berger",
	"Sam Garbarski",
	"Melville Shavelson",
	"Don Cheadle",
	"Jerry Lewis",
	"Richard Boleslawski",
	"Claude Miller",
	"Naomi Kawase",
	"Zoltan Korda",
	"Fred Cavayé",
	"David Wnendt",
	"John Duigan",
	"Percy Adlon",
	"Martin Koolhoven",
	"H. Bruce Humberstone",
	"Pablo Berger",
	"Jim Kohlberg",
	"Hsiao-Hsien Hou",
	"Stuart Heisler",
	"Yann Demange",
	"Mikkel Nørgaard",
	"Alexei Popogrebsky",
	"Bruno Dumont",
	"Jasmila Zbanic",
	"Don Roos",
	"Allan Arkush",
	"Nicolas Gessner",
	"Tage Danielsson",
	"Carl Boese",
	"John Flynn",
	"Tom Gries",
	"Harald Reinl",
	"Tom Kalin",
	"Diane Keaton",
	"Jacques Doillon",
	"Mary Harron",
	"Jack Smight",
	"Baran bo Odar",
	"Wallace Worsley",
	"Donald Crisp",
	"John Wayne",
	"Alan Johnson",
	"Kon Ichikawa",
	"Marcel Camus",
	"Dariush Mehrjui",
	"Xiaoshuai Wang",
	"Wojciech Smarzowski",
	"Anna Muylaert",
	"Leni Riefenstahl",
	"Brad McGann",
	"Marcos Efron",
	"Claude Lanzmann",
	"Roy William Neill",
	"Jack Arnold",
	"Elissa Down",
	"Michael Berry",
	"Lee Chang-dong",
	"Sean Baker",
	"Icíar Bollaín",
	"Sijie Dai",
	"Byambasuren Davaa",
	"Maurice Pialat",
	"Fielder Cook",
	"Denis Dercourt",
	"Brian Gilbert",
	"Edgar Reitz",
	"Billy Kent",
	"David Evans",
	"Guy Green",
	"Alan Rudolph",
	"Toshio Matsumoto",
	"Claude Pinoteau",
	"Mike Barker",
	"André De Toth",
	"Roland Suso Richter",
	"Antonio Negret",
	"Albert Magnoli",
	"Seth Holt",
	"Reza Bagher",
	"Grigoriy Kozintsev",
	"William Cameron Menzies",
	"Ken Burns",
	"Graeme Clifford",
	"Gérard Corbiau",
	"Jacques Deray",
	"Juan Pablo Rebella",
	"Pablo Stoll",
	"Philippe Le Guay",
	"Céline Sciamma",
	"Tony Gatlif",
	"Howard Hughes",
	"Fina Torres",
	"Jan-Ole Gerster",
	"Mohsen Makhmalbaf",
	"Atiq Rahimi",
	"Cao Hamburger",
	"Shana Feste",
	"Anthony Waller",
	"James Parrott",
	"John Turturro",
	"Anusha Rizvi",
	"Keisuke Kinoshita",
	"Moustapha Akkad",
	"Allan Dwan",
	"Jack Hill",
	"Alfred E. Green",
	"Marco Bellocchio",
	"Jan Komasa",
	"Vicco von Bülow",
	"Rolf Schübel",
	"Chris Kraus",
	"Anne Wheeler",
	"Lina Wertmüller",
	"Valerio Zurlini",
	"Daniel Vigne",
	"Detlev Buck",
	"George Miller",
	"Frédéric Fonteyne",
	"Özer Kiziltan",
	"Stephen Walker",
	"Sally George",
	"Miklós Jancsó",
	"Sergey Loznitsa",
	"Ted Kotcheff",
	"Jaromil Jires",
	"Marlon Brando",
	"Stuart Millar",
	"Dominik Moll",
	"Philip D'Antoni",
	"Irving Rapper",
	"Doris Dörrie",
	"Andreas Öhman",
	"Jerry Kramer",
	"John Brahm",
	"Helmut Dietl",
	"Lee H. Katzin",
	"Patricia Riggen",
	"Gene Wilder",
	"George Fitzmaurice",
	"Béla Tarr",
	"Frank Tuttle",
	"Pavel Chukhray",
	"Antonello Grimaldi",
	"Dietrich Brüggemann",
	"Urszula Antoniak",
	"Jimmy T. Murakami",
	"Bob Smeaton",
	"Rex Ingram",
	"Vittorio Taviani",
	"Paolo Taviani",
	"Bertrand Blier",
	"Juraj Herz",
	"Compton Bennett",
	"Joseph Cedar",
	"Jane Anderson",
	"Martha Coolidge",
	"Mario Van Peebles",
	"Roy Ward Baker",
	"Steve Buscemi",
	"Carl Schenkel",
	"Giulio Petroni",
	"Gillies MacKinnon",
	"Péter Bacsó",
	"Grigoriy Aleksandrov",
	"Marcus H. Rosenmüller",
	"Erik Skjoldbjærg",
	"Wesley Ruggles",
	"David Koepp",
	"Amy Berg",
	"Srdjan Dragojevic",
	"Marco Ferreri",
	"Heinz Dunkhase",
	"Fruit Chan",
	"Thomas Balmès",
	"Joseph Zito",
	"Lisa Langseth",
	"Allen Baron",
	"Andreas Prochaska",
	"Ming-liang Tsai",
	"Ousmane Sembene",
	"Robert Ellis Miller",
	"John Singleton",
	"Sergei Bodrov",
	"Vincent Grashaw",
	"Udayan Prasad",
	"Jerzy Kawalerowicz",
	"Vicente Aranda",
	"Eliseo Subiela",
	"Stanislaw Bareja",
	"Catherine Breillat",
	"Sérgio Machado",
	"Joann Sfar",
	"Helmut Weiss",
	"Rodrigo Plá",
	"Viktor Chouchkov",
	"Derek Jarman",
	"Francis Veber",
	"Cãlin Peter Netzer",
	"Claude Zidi",
	"Claudia Llosa",
	"Lew Landers",
	"Yaron Zilberman",
	"Kon Ichikawa",
	"Krzysztof Krauze",
	"Michael Schultz",
	"Lucía Puenzo",
	"Peter Masterson",
	"Gustave Kervern",
	"Benoît Delépine",
	"Serge Korber",
	"Jack Haley Jr.",
	"Bahram Beyzaie",
	"Claude Autant-Lara",
	"Pierre Granier-Deferre",
	"Budd Boetticher",
	"Bretaigne Windust",
	"Claire Denis",
	"Peter Ho-Sun Chan",
	"Seijirô Kôyama",
	"Olivier Marchal",
	"Erle C. Kenton",
	"Jack Gold",
	"Eytan Fox",
	"Liv Ullmann",
	"Marina Zenovich",
	"Raoul Peck",
	"Fons Rademakers",
	"John S. Robertson",
	"Marshall Neilan",
	"Sidney Gilliat",
	"Bruno Nuytten",
	"Carlos Sorin",
	"Jean-Paul Salomé",
	"Florin Serban",
	"Maïwenn",
	"Simon Verhoeven",
	"Frank Pierson",
	"Cedric Gibbons",
	"Mehdi Charef",
	"Im Sang-soo",
	"Pablo Trapero",
	"Feo Aladag",
	"Achim von Borries",
	"Eric Valette",
	"Lisa Barros D'Sa",
	"Glenn Leyburn",
	"Elio Petri",
	"Jerzy Hoffman",
	"Xavier Giannoli",
	"Nils Gaup",
	"Coline Serreau",
	"James Hill",
	"Václav Vorlícek",
	"Andrew Solt",
	"Alberto Lattuada",
	"Sebastián Silva",
	"Emilio Martínez Lázaro",
	"Allison Anders",
	"Kjell Sundvall",
	"Julie Bertuccelli",
	"Tony Bui",
	"Zaza Urushadze",
	"André Hunebelle",
	"Metodi Andonov",
	"Semih Kaplanoglu",
	"Wladyslaw Pasikowski",
	"Alex Rivera",
	"Rowland V. Lee",
	"Fred Coe",
	"Ray Goossens",
	"Steve Jacobs",
	"Benjamin Heisenberg",
	"Özgür Yildirim",
	"Giulio Ricciarelli",
	"Benito Zambrano",
	"Yurek Bogayevicz",
	"Pascale Ferran",
	"Russell Rouse",
	"Fred M. Wilcox",
	"Mark Rosman",
	"Eskil Vogt",
	"James B. Harris",
	"Lewis John Carlino",
	"Gus Meins",
	"Heinrich Breloer",
	"Shôhei Imamura",
	"Hans Petter Moland",
	"Ladislao Vajda",
	"Isabelle Mergault",
	"Riad Sattouf",
	"Herman Shumlin",
	"Jessica Hausner",
	"Alfred Vohrer",
	"Robert Greenwald",
	"Quan'an Wang",
	"Wolfgang Staudte",
	"Helmut Käutner",
	"Stanley Kwan",
	"Reha Erdem",
	"Serge Bourguignon",
	"Harold Young",
	"Stijn Coninx",
	"Zalman King",
	"Paul Justman",
	"Hugo Rodríguez",
	"Dick Richards",
	"Roberto Andò",
	"Ub Iwerks",
	"Damjan Kozole",
	"Stanislav Rostotskiy",
	"Paul Cox",
	"Curtis Bernhardt",
	"Elliott Nugent",
	"Robert Enrico",
	"Rachid Bouchareb",
	"Costas Ferris",
	"Daniel Burman",
	"Harold S. Bucquet",
	"Bertrand Bonello",
	"Jerry Jameson",
	"Anthony Perkins",
	"Mikio Naruse",
	"Damiano Damiani",
	"Irving Lerner",
	"Nacer Khemir",
	"Nir Bergman",
	"Stephen Gyllenhaal",
	"Joachim Lafosse",
	"Saverio Costanzo",
	"Brad Mirman",
	"Richard T. Heffron",
	"Francesco Rosi",
	"Vera Chytilová",
	"Michael Verhoeven",
	"Hong Sang-soo",
	"Konstantin Lopushanskiy",
	"Dick Maas",
	"Saul Bass",
	"Henning Carlsen",
	"Aleksandr Dovzhenko",
	"Aleksey German",
	"King Hu",
	"Joe May",
	"Sally Potter",
	"Andrzej Jakimowski",
	"Walter Ruttmann",
	"Lucian Pintilie",
	"A. Edward Sutherland",
	"Dani Levy",
	"Anthony Fabian",
	"Andrew Birkin",
	"Adrián Biniez",
	"Yasemin Samdereli",
	"Yi'nan Diao",
	"Edward Anderson",
	"James Goldstone",
	"Hardy Martins",
	"Larisa Shepitko",
	"Zoltán Fábri",
	"Vinko Bresan",
	"Melvin Van Peebles",
	"Warwick Thornton",
	"Aleksandr Proshkin",
	"Peter Fonda",
	"James Edward Grant",
	"Luigi Comencini",
	"Frank Beyer",
	"Sergiu Nicolaescu",
	"Pete Travis",
	"Harry O. Hoyt",
	"Arnaud Larrieu",
	"Jean-Marie Larrieu",
	"Vishal Bhardwaj",
	"Kevin Asch",
	"Mitja Okorn",
	"Raymond Lee",
	"Abel Gance",
	"Dino Risi",
	"Raúl Ruiz",
	"Georges Lautner",
	"Tadeusz Chmielewski",
	"Herbert J. Biberman",
	"Cãtãlin Mitulescu",
	"Gianfranco Rosi",
	"Gregory Ratoff",
	"Yuriy Chulyukin",
	"Larry Peerce",
	"Ben Sombogaart",
	"Vsevolod Pudovkin",
	"Krzysztof Zanussi",
	"Marc Allégret",
	"John Waters",
	"Richard Wallace",
	"Petr Zelenka",
	"Catherine Corsini",
	"Emmanuel Mouret",
	"Robert D. Webb",
	"Vladimir Motyl",
	"Lowell Sherman",
	"Bernard Knowles",
	"Marcelo Piñeyro",
	"Rob Cohen",
	"Delphine Coulin",
	"Muriel Coulin",
	"Malgorzata Szumowska",
	"Bruno Barreto",
	"George Melford",
	"Marcin Wrona",
	"Étienne Chatiliez",
	"Dimitri Kirsanoff",
	"Kurt Hoffmann",
	"David Leland",
	"Frauke Finsterwalder",
	"Ralf Huettner",
	"Ann Turner",
	"John Derek",
	"Rama Burshtein",
	"Krisztina Goda",
	"Giuseppe De Santis",
	"Piotr Trzaskalski",
	"Matthias Glasner",
	"Victor Saville",
	"Norman Foster",
	"Sylvain Estibal",
	"John G. Blystone",
	"Carl Gottlieb",
	"Marcus Mittermeier",
	"Julia Loktev",
	"Douglas Hickox",
	"Tomás Gutiérrez Alea",
	"Heiner Carow",
	"Christian Schwochow",
	"Jan Nemec",
	"Benoît Jacquot",
	"Andrés Wood",
	"Gianni Di Gregorio",
	"Shi-Zheng Chen",
	"Anne Sewitsky",
	"Benedikt Erlingsson",
	"Joseph Anthony",
	"Pepe Danquart",
	"Sharon Maymon",
	"Tal Granit",
	"Christopher N. Rowley",
	"Isidro Ortiz",
	"Tomasz Baginski",
	"Andrzej Munk",
	"Antonio Hernández",
	"Nils Malmros",
	"Adolfo Aristarain",
	"Lucrecia Martel",
	"Alfred J. Goulding",
	"Michael Rowe",
	"Gabriel Pascal",
	"Lothar Mendes",
	"Luc Dionne",
	"Michael McGowan",
	"Mani Ratnam",
	"Rune Denstad Langlo",
	"Shira Geffen",
	"Matt Ross",
	"Morris Engel",
	"Etgar Keret",
	"Walerian Borowczyk",
	"Emilio Maillé",
	"Alf Sjöberg",
	"Konrad Wolf",
	"Roberto Gavaldón",
	"Robert Florey",
	"Dominik Graf",
	"Annette K. Olesen",
	"Clarence G. Badger",
	"Zhou Sun",
	"Frédéric Schoendoerffer",
	"Shirin Neshat",
	"Robert Allan Ackerman",
	"Tudor Giurgiu",
	"Joona Tena",
	"Joe Camp",
	"Jacques Rivette",
	"Christian-Jaque",
	"Emil Loteanu",
	"Christopher Hampton",
	"David Butler",
	"Yorgos Tzavellas",
	"Max Reinhardt",
	"Neele Leana Vollmar",
	"Lukasz Palkowski",
	"Rezo Chkheidze",
	"Sebastián Lelio",
	"Giacomo Battiato",
	"Andrucha Waddington",
	"Aleksi Salmenperä",
	"Albert Ter Heerdt",
	"Károly Makk",
	"Dorota Kedzierzawska",
	"Jerzy Stuhr",
	"Robert Glinski",
	"Marek Piwowski",
	"Ryszard Bugajski",
	"Jo Baier",
	"Boris Khlebnikov",
	"Pen-Ek Ratanaruang",
	"Vladimir Chebotaryov",
	"Gennadiy Kazanskiy",
	"Karen Arthur",
	"José Henrique Fonseca",
	"Paul Crowder",
	"John Dower",
	"Akiz",
	"Gianni Amelio",
	"George W. Hill",
	"Monte Hellman",
	"William Beaudine",
	"Arne Skouen",
	"Gustav Machatý",
	"Stéphane Brizé",
	"Samira Makhmalbaf",
	"Servando González",
	"Hermine Huntgeburth",
	"Michael Schroeder",
	"Mu Fei",
	"Marc Fitoussi",
	"Maximilian Erlenwein",
	"Lisa Ohlin",
	"Joaquín Oristrell",
	"Peter Godfrey",
	"Kåre Bergstrøm",
	"Ray Müller",
	"Michael Oblowitz",
	"Alain Tanner",
	"Feliks Falk",
	"Janusz Majewski",
	"Abel Ferrara",
	"Byron Haskin",
	"Nikos Koundouros",
	"Roy Rowland",
	"Antoinette Beumer",
	"Manuel Gómez Pereira",
	"James Neilson",
	"Josef von Báky",
	"Charles Lamont",
	"Jesper W. Nielsen",
	"Anders Nilsson",
	"Jean-Paul Lilienfeld",
	"Richard Schickel",
	"Anna Justice",
	"Ole Christian Madsen",
	"Marcel Varnel",
	"Maria Ripoll",
	"Michael Roemer",
	"Ralf Westhoff",
	"Bernard Borderie",
	"Lian Lunson",
	"Michel Deville",
	"Dorothy Arzner",
	"Busby Berkeley",
	"Henri Decoin",
	"Curt Siodmak",
	"Albert Parker",
	"Borys Lankosz",
	"Roger Christian",
	"Felix van Groeningen",
	"Ilya Frez",
	"Hannes Stöhr",
	"Gerd Oswald",
	"Martin Asphaug",
	"Andrew L. Stone",
	"Elaine May",
	"Safi Yazdanian",
	"Martti Helde",
	"Sacha Polak",
	"Peter Tewksbury",
	"John Rich",
	"Jack Sher",
	"Evelyn Purcell",
	"Katrin Gebbe",
	"Edward Ludwig",
	"Manoel de Oliveira",
	"Friðrik Þór Friðriksson",
	"Chris Menges",
	"William K. Howard",
	"Géza von Radványi",
	"Pál Fejös",
	"Dev Benegal",
	"Kari Skogland",
	"Yuan Zhang",
	"Henrik Ruben Genz",
	"Johnnie To",
	"Tim Whelan",
	"Carmine Gallone",
	"Juan Carlos Tabío",
	"Tomas Villum Jensen",
	"Howard Zieff",
	"Éléonore Faucher",
	"Bernard Queysanne",
	"Hubert Cornfield",
	"Audrius Juzenas",
	"Ida Lupino",
	"Mary Lambert",
	"Niki Stein",
	"Jochen Alexander Freydank",
	"Daniel Wolfe",
	"Sven Taddicken",
	"Alexandra Leclère",
	"Fabrice Joubert",
	"Nisha Ganatra",
	"Maria Schrader",
	"Yves Allégret",
	"Lloyd Bacon",
	"Alain Robbe-Grillet",
	"Leontine Sagan",
	"Pawel Pawlikowski",
	"Moshé Mizrahi",
	"Kazimierz Kutz",
	"Aleksandr Alov",
	"Vladimir Naumov",
	"Pernille Fischer Christensen",
	"Alan Bridges",
	"Ray Enright",
	"Clement Virgo",
	"Gottfried Reinhardt",
	"Hal Roach",
	"Matías Bize",
	"Michele Lupo",
	"Yang Zhang",
	"José Luis Garci",
	"Arthur Ripley",
	"Maximilian Schell",
	"Johannes Naber",
	"Karen Shakhnazarov",
	"Hiner Saleem",
	"Leszek Dawid",
	"Richard Whorf",
	"Hideo Nakata",
	"Barnaby Southcombe",
	"Andy De Emmony",
	"Piotr Szulkin",
	"Juan Antonio Bardem",
	"Philippe de Broca",
	"Sergey Gerasimov",
	"Abram Room",
	"Roy Del Ruth",
	"Iosif Kheifits",
	"Aleksandr Askoldov",
	"Rafi Pitts",
	"Mikkel Munch-Fals",
	"Robert Thalheim",
	"Nana Dzhordzhadze",
	"Beeban Kidron",
	"Emmanuel Mouret",
	"Christian Marquand",
	"Kenneth Bi",
	"John Berry",
	"Steve Sekely",
	"Antonio Mercero",
	"Seyfi Teoman",
	"Sylvia Chang",
	"Paul Morrison",
	"Tomasz Konecki",
	"Nicky Phelan",
	"Kai Wessel",
	"Lars Becker",
	"Alain Cavalier",
	"Claude Goretta",
	"Marcel L'Herbier",
	"Péter Gothár",
	"Léa Pool",
	"Oldrich Lipský",
	"Irving Reis",
	"Hobart Henley",
	"Jan P. Matuszynski",
	"Andres Veiel",
	"José Giovanni",
	"Anthony Pelissier",
	"Leon Ichaso",
	"Stuart Hagmann",
	"F. Richard Jones",
	"Ryan Eslinger",
	"Cathy Randall",
	"JK Youn",
	"Don McKellar",
	"Natalie Portman",
	"Petr Kazda",
	"Rajko Grlic",
	"Tomás Weinreb",
	"Andrey Tutyshkin",
	"Anno Saul",
	"Dick Powell",
	"Alain Delon",
	"Henry Edwards",
	"Serge Bromberg",
	"Wolfgang Büld",
	"Aleksander Ford",
	"Alexander Kluge",
	"Maciej Pieprzyca",
	"James Cruze",
	"Aleksandr Zarkhi",
	"Felix E. Feist",
	"Kinji Fukasaku",
	"Richard Oswald",
	"John Francis Dillon",
	"Slawomir Fabicki",
	"Antonio Pietrangeli",
	"Zoltán Huszárik",
	"Masahiro Shinoda",
	"Robert Parrish",
	"Max Linder",
	"Vincent J. Donehue",
	"Rainer Kaufmann",
	"Dror Zahavi",
	"Maxwell Shane",
	"Je-yong Lee",
	"Angelina Maccarone",
	"Marcos Bernstein",
	"Karl Hartl",
	"Lisa Siwe",
	"Hao Ning",
	"Dominique Deruddere",
	"Nick Castle",
	"Miguel Gomes",
	"Vasili Pichul",
	"Charles Frend",
	"Noémie Lvovsky",
	"Tomy Wigand",
	"Fisher Stevens",
	"Pedro Costa",
	"Hugo Fregonese",
	"Fabienne Berthaud",
	"Ralph Levy",
	"George Schaefer",
	"Jonas Carpignano",
	"Rudi Rosenberg",
	"Magdalena Piekorz",
	"Werner Jacobs",
	"Harald Philipp",
	"Hape Kerkeling",
	"Otar Iosseliani",
	"Fernando E. Solanas",
	"Jean Delannoy",
	"Sacha Guitry",
	"Waldemar Krzystek",
	"Jan Jakub Kolski",
	"Maurice Tourneur",
	"Vincent Sherman",
	"Yoshishige Yoshida",
	"Joseph Henabery",
	"Peter Sehr",
	"Yonggang Wu",
	"Rolan Bykov",
	"Jean-Pierre Mocky",
	"Harry d'Abbadie d'Arrast",
	"Sidney Hayers",
	"Mikko Niskanen",
	"Oskar Santos",
	"Maria Peters",
	"Boaz Davidson",
	"Sylwester Checinski",
	"Tomer Heymann",
	"Marie Noëlle",
	"Reza Dormishian",
	"Lars Büchel",
	"Johannes Schaaf",
	"Vladimír Morávek",
	"José Quintero",
	"Changwei Gu",
	"Riccardo Freda",
	"David Hugh Jones",
	"Christian Vincent",
	"Philippe Lesage",
	"Ray C. Smallwood",
	"Jacek Borcuch",
	"Raja Amari",
	"Dalia Hager",
	"Beto Brant",
	"Ute Wieland",
	"Pieter Kramer",
	"Axel von Ambesser",
	"Mack Sennett",
	"Tinto Brass",
	"Giuliano Carnimeo",
	"Werner Schweizer",
	"Mikhail Romm",
	"James Algar",
	"Ewald André Dupont",
	"Boris Barnet",
	"Irving Cummings",
	"Aleksandar Petrovic",
	"Reinhard Hauff",
	"Robert Guédiguian",
	"Jean-Pierre Améris",
	"Wojciech Marczewski",
	"David Hare",
	"Bert Haanstra",
	"Dror Moreh",
	"Salvatore Samperi",
	"Jai-hong Juhn",
	"Jirí Trnka",
	"Dudley Nichols",
	"Hella Joof",
	"Wilhelm Thiele",
	"Arnold Fanck",
	"Roger Young",
	"Rogelio A. González",
	"Christian E. Christiansen",
	"Wen Jiang",
	"Hiroshi Shimizu",
	"Ulrich Köhler",
	"Leslie Howard",
	"Alain Jessua",
	"Willis Goldbeck",
	"Quentin Lawrence",
	"Jacek Bromski",
	"Stuart Gillard",
	"Adrian Sitaru",
	"Thomas Arslan",
	"Férid Boughedir",
	"Peter Lichtefeld",
	"Dante Lam",
	"Richard Sale",
	"Tadeusz Konwicki",
	"Andrey Smirnov",
	"Arne Mattsson",
	"David Greene",
	"Hans W. Geissendörfer",
	"John Irvin",
	"Jan Kidawa-Blonski",
	"Cheol-su Park",
	"Arthur Robison",
	"Ralph Thomas",
	"Marzieh Makhmalbaf",
	"Desmond Davis",
	"Kim Nguyen",
	"Howard Higgin",
	"Michel Spinosa",
	"Georg Maas",
	"Kaspar Heidelbach",
	"Vladimír Michálek",
	"Naoko Ogigami",
	"Jirí Krejcík",
	"Ante Babaja",
	"Mariano Llinás",
	"Riri Riza",
	"Toa Fraser",
	"Aida Begic",
	"Edward H. Griffith",
	"Chris Bernard",
	"Antoine de Caunes",
	"Timothy Linh Bui",
	"Piers Haggard",
	"Maciej Slesicki",
	"Paul May",
	"Henri Safran",
	"Arild Andresen",
	"Anne Zohra Berrached",
	"Tobias Nölle",
	"Thomas Grube",
	"Heinz Schirk",
	"Denys de La Patellière",
	"Aarón Fernández Lesur",
	"James B. Clark",
	"Dieter Pröttel",
	"Helma Sanders-Brahms",
	"Kira Muratova",
	"Brian Percival",
	"Mani Haghighi",
	"Janusz Zaorski",
	"Vasiliy Shukshin",
	"George B. Seitz",
	"Claude Binyon",
	"Lewis Seiler",
	"Lucy Walker",
	"Peter F. Bringmann",
	"Jeffrey Kusama-Hinte",
	"Edmond T. Gréville",
	"Jean-Pierre Sinapi",
	"Manuel Gutiérrez Aragón",
	"Hilmar Oddsson",
	"Roy Boulting",
	"Jacques Rouffio",
	"Eric-Emmanuel Schmitt",
	"Greg Zglinski",
	"Dominic Savage",
	"Alfred Weidenmann",
	"Edwin L. Marin",
	"Claude Faraldo",
	"Dror Shaul",
	"Matti Geschonneck",
	"Peter Fleischmann",
	"Bartosz Konopka",
	"Etienne Périer",
	"Josée Dayan",
	"Ryszard Zatorski",
	"Jacques Dorfmann",
	"Måns Herngren",
	"William A. Graham",
	"Allen Reisner",
	"Antonio Chavarrías",
	"Robert B. Sinclair",
	"Sun-Woo Jang",
	"Xawery Zulawski",
	"Bouli Lanners",
	"Stanislaw Mucha",
	"Oleg Novkovic",
	"Leo C. Popkin",
	"Edward Berger",
	"Mitchell Lichtenstein",
	"Anna Novion",
	"Antonio Banderas",
	"Esther Gronenborn",
	"Jakob Lass",
	"Gustaf Molander",
	"Henri Colpi",
	"Glauber Rocha",
	"Ebrahim Golestan",
	"Jean Grémillon",
	"Ariane Mnouchkine",
	"Ruy Guerra",
	"Marion Gering",
	"Stephen Roberts",
	"Benedek Fliegauf",
	"William Castle",
	"Hark Bohm",
	"Marco Vicario",
	"Michael Gutmann",
	"Robert van Ackeren",
	"Nick Grinde",
	"Jan Hrebejk",
	"Pierre Pinaud",
	"Frédéric Mitterrand",
	"Harold Prince",
	"Adolf Winkelmann",
	"Yesim Ustaoglu",
	"Lionel Barrymore",
	"Buzz Kulik",
	"Nathan Juran",
	"Peter Lorre",
	"Leslie Fenton",
	"Stuart Gilmore",
	"Thomas Durchschlag",
	"Alf Brustellin",
	"Alan Gibson",
	"Hans Quest",
	"Miguel Albaladejo",
	"Julie Gavras",
	"Stephan Brenninkmeijer",
	"Bruno Podalydès",
	"James Flood",
	"Aleksandr Zguridi",
	"Slatan Dudow",
	"Lars-Gunnar Lotz",
	"Casper Wrede",
	"Dusan Milic",
	"Mark Dornford-May",
	"Rafael Lewandowski",
	"Pia Marais",
	"Chico Teixeira",
	"Torun Lian",
	"Peter Gorski",
	"Sven Unterwaldt Jr.",
	"Marten Persiel",
	"Mario Soffici",
	"Janusz Morgenstern",
	"Jaime de Armiñán",
	"Jean-Marie Straub",
	"Lambert Hillyer",
	"Álex de la Iglesia",
	"Karl Grune",
	"David Burton",
	"Fernando León de Aranoa",
	"Monta Bell",
	"Yves Boisset",
	"Eberhard Fechner",
	"Maciej Dejczer",
	"Billy Bob Thornton",
	"Radu Jude",
	"Christoph Hochhäusler",
	"Julian Pölsler",
	"Wolfgang Kohlhaase",
	"Jesús Franco",
	"Wolfgang Liebeneiner",
	"Joseph Pevney",
	"Renato Castellani",
	"Dariusz Gajewski",
	"Jean-Loup Hubert",
	"Aleksandr Rogozhkin",
	"Tomasz Wiszniewski",
	"Witold Leszczynski",
	"Serge Leroy",
	"Teresa Villaverde",
	"Stefan Arsenijevic",
	"Frank Launder",
	"Tony Ayres",
	"Doze Niu",
	"Dieter Wedel",
	"Didi Danquart",
	"Larry Cohen",
	"Joachim Masannek",
	"Raoul Lévy",
	"Wolfgang Becker",
	"David Hemmings",
	"Antoni Krauze",
	"Ephraim Kishon",
	"Henk Handloegten",
	"Arto Koskinen",
	"Kevin Billington",
	"Phil Jutzi",
	"Jaroslav Papousek",
	"Zrinko Ogresta",
	"Marion Hänsel",
	"Emmanuelle Bercot",
	"Stina Werenfels",
	"Robert Enders",
	"Natalia Smirnoff",
	"Alejandro Fernández Almendras",
	"Roberto Castón",
	"Nanouk Leopold",
	"Maja Weiss",
	"Bernhard Grzimek",
	"Tomasz Wasilewski",
	"Jerry Hopper",
	"Rajnesh Domalpalli",
	"Harold D. Schuster",
	"Anthony Simmons",
	"Renars Vimba",
	"Kenneth MacPherson",
	"Brillante Mendoza",
	"Willi Forst",
	"Roland Klick",
	"Leopoldo Torre Nilsson",
	"Sergei Yutkevich",
	"J. Searle Dawley",
	"Irina Poplavskaya",
	"Peter Schamoni",
	"Nicolae Margineanu",
	"Arnold Laven",
	"Georg Tressler",
	"Bernhard Sinkel",
	"Paul Czinner",
	"Henry Cornelius",
	"Lois Weber",
	"Francesca Comencini",
	"Walter Grauman",
	"Wojciech Wójcik",
	"Paul Powell",
	"Karl Heinz Martin",
	"Jürgen Roland",
	"Rainer Erler",
	"Frank Wisbar",
	"May Spils",
	"James Young",
	"Xaver Schwarzenberger",
	"Züli Aladag",
	"Anna Melikyan",
	"Wolf Gremm",
	"Behnam Behzadi",
	"Marcin Krzysztalowicz",
	"Gerhard Klein",
	"Philippe Labro",
	"Jan Schomburg",
	"Otto Alexander Jahrreiss",
	"Manijeh Hekmat",
	"Alexander Adolph",
	"Denis Chouinard",
	"Gerhard Lamprecht",
	"Peter Keglevic",
	"Stephan Wagner",
	"Paul L. Stein",
	"Ognjen Svilicic",
	"Florestano Vancini",
	"Michal Rosa",
	"Denis Côté",
	"Katarzyna Roslaniec",
	"Dragan Marinkovic",
	"Krzysztof Lukaszewicz",
	"Jaroslaw Zamojda",
	"Ineke Houtman",
	"Safy Nebbou",
	"Jan Batory",
	"Aage Rais-Nordentoft",
	"Roberto Moreira",
	"Bruno Chiche",
	"James Steven Sadwith",
	"Elmer Clifton",
	"Sonja Heiss",
	"Ulli Baumann",
	"Chao Yang",
	"Henner Winckler",
	"Urs Odermatt",
	"Robert N. Bradbury",
	"Steve Gebhardt",
	"Marialy Rivas",
	"Michel Lang",
	"Erich Engels",
	"Kinga Debska",
	"Peter Kahane",
	"Mathieu Denis",
	"Tata Amaral",
	"Sigi Rothemund",
	"Stanislaw Tym",
	"Valeska Grisebach",
	"Angela Schanelec",
	"Mauritz Stiller",
	"Amos Gitai",
	"Werner Schroeter",
	"Kurt Maetzig",
	"Stanislaw Rózewicz",
	"Wanda Jakubowska",
	"Rudolf Jugert",
	"René Allio",
	"Egon Günther",
	"Nyrki Tapiovaara",
	"Leo Penn",
	"Czeslaw Petelski",
	"Markus Imboden",
	"Alberto Bevilacqua",
	"Peter Ustinov",
	"Ranald MacDougall",
	"Mika Kaurismäki",
	"Rolf Thiele",
	"George Abbott",
	"Liliana Cavani",
	"Robert Reinert",
	"Gustav Ucicky",
	"Jan Schütte",
	"Conor McPherson",
	"Filip Bajon",
	"Henry Cass",
	"Jacques Bral",
	"Buddhadev Dasgupta",
	"Jack Hively",
	"Bernd Böhlich",
	"Przemyslaw Wojcieszek",
	"Kazimierz Karabasz",
	"Peter Timm",
	"Brian Large",
	"Kari Paljakka",
	"Damien Odoul",
	"Sébastien Grall",
	"Hajo Gies",
	"Teresa Kotlarczyk",
	"Vanessa Jopp",
	"Birgit Möller",
	"Ivan Nichev",
	"Milan Cieslar",
	"Anahí Berneri",
	"Luis Trenker",
	"Hans Deppe",
	"Werner Klingler",
	"Lupu Pick",
	"Nicolai Albrecht",
	"Imo Moszkowicz",
	"Peter Patzak",
	"Vincenzo Marra",
	"Sergio Citti",
	"William Nigh",
	"Paula Markovitch",
	"Vasily Zhuravlyov",
	"Peter Wood",
	"Eric Till",
	"Ben Hopkins",
	"Alberto Rodríguez",
	"Wiktor Grodecki",
	"Oliver Storz",
	"Benjamin Gilmour",
	"Filip Van Neyghem",
	"Atsushi Funahashi",
	"Stanislaw Lenartowicz",
	"Phil Goldstone",
	"Marina Lyubakova",
	"Sophie Fillières",
	"Algimantas Puipa",
	"Jean-Marc Moutout",
	"Leo Khasin",
	"Ina Weisse",
	"Friedemann Fromm",
	"Nicole Weegmann",
	"Mijke de Jong",
	"Erik Charell",
	"Reinhold Schünzel",
	"Connie Walter",
	"Wolfgang Schleif",
	"Rita Horst",
	"Klaus Krämer",
	"William J. Cowen",
	"Yu-Chieh Cheng",
	"Dariusz Jablonski",
	"Thomas Engel",
	"Eduard von Borsody",
	"Berit Madsen",
	"Eckhart Schmidt",
	"Anaïs Barbeau-Lavalette",
	"Ricky Tognazzi",
	"María Luisa Bemberg",
	"Samuel Bischoff",
	"Ferdinando Baldi",
	"André Farwagi",
	"Eike Besuden",
	"Giorgio Capitani",
	"Yuriy Moroz",
	"Dana Ranga",
	"Ryszard Brylski",
	"Agnieszka Smoczynska",
	"Marek Lechki",
	"Adrian Wills",
	"Daniel Harrich",
	"Fred Guiol",
	"Heidi Maria Faisst",
	"Hal Walker",
	"Sergiu Prodan",
	"Johnny Ma",
	"Lucy Mulloy",
	"Samuel Collardey",
	"Carsten Fiebeler",
	"Stefan Krohmer",
	"Aleksandr Mindadze",
	"Jung-chi Chang",
	"Florian Schwarz",
	"Constantine Giannaris",
	"Theo Mezger",
	"Gil Mehmert",
	"Sathyan Ramesh",
	"Alex Anwandter",
	"Franz Josef Gottlieb",
	"Márta Mészáros",
	"Kwon-taek Im",
	"Jacques Feyder",
	"Markus Imhoof",
	"Thomas Brasch",
	"Magdalena Lazarkiewicz",
	"Peter Zadek",
	"Dudley Murphy",
	"Fyodor Otsep",
	"Hans-Jürgen Syberberg",
	"Alan Crosland",
	"Hans Jürgen Pohland",
	"Dito Tsintsadze",
	"Guy Nattiv",
	"Peter Lilienthal",
	"Nicos Perakis",
	"Tomasz Zygadlo",
	"Niklaus Schilling",
	"Lech Majewski",
	"Karel Kachyna",
	"Antonio Skármeta",
	"Carl Schultz",
	"Wolfgang Murnberger",
	"Wolfgang Glück",
	"Klaus Maria Brandauer",
	"Robert A. Stemmle",
	"Frank R. Strayer",
	"Angelo Cianci",
	"Lu Zhang",
	"Hans Steinhoff",
	"Min-Yong Lee",
	"Sophie Heldman",
	"Sergio Rubini",
	"Hans-Christoph Blumenberg",
	"Norbert Kückelmann",
	"Franz Peter Wirth",
	"Will Tremper",
	"Jürgen Böttcher",
	"Yong-hi Yang",
	"Ulla Wagner",
	"André Schäfer",
	"Marcus Vetter",
	"Seung-bin Baek",
	"Dominik Wessely",
	"Luigi Falorni",
	"Salvatore Mereu",
	"Pierre Sanoussi-Bliss",
	"Brian M. Cassidy",
	"Melanie Shatzky",
	"Sung Hyung Cho",
	"Hartmut Schoen",
	"Djamila Sahraoui",
	"Stefan Schwietert",
	"Curt Goetz",
	"Shunkai Mizuho",
	"Rolf Hansen",
	"Falk Harnack",
	"Ottomar Domnick",
	"Witold Adamek",
	"Palle Kjærulff-Schmidt",
	"Kaori Momoi",
	"Marek Nowicki",
	"Franz Antel",
	"Brice Cauvin",
	"Przemyslaw Reut",
	"Asli Özge",
	"Kerstin Ahlrichs",
	"Zoltán Kamondi",
	"Gerald Mayer",
	"Faye Dunaway",
	"Marc-Andreas Bochert",
	"Nina Grosse",
	"Rolf Hädrich",
	"Christoph Schaub",
	"Krystyna Janda",
	"Christophe Blanc",
	"Chang-ho Cho",
	"Herbert Achternbusch",
	"Peeter Simm",
	"Dominique Cabrera",
	"Katharina Otto-Bernstein",
	"Tim Trageser",
	"Bernd Schadewald",
	"Georg Misch",
	"Marianne Lüdcke",
	"John Reinhardt",
	"Georg Hurdalek",
	"Rudolf Zehetgruber",
	"Andreas Kleinert",
	"Marc Hertel",
	"Jakob Ziemnicki",
	"Louis-Julien Petit",
	"Emir Baigazin",
	"Eoin Moore",
	"Manfred Stelzer",
	"Ernest Abdyjaparov",
	"Claudia Prietzel",
	"Franziska Buch",
	"Anna Plutecka-Mesjasz",
	"Klaus Lemke",
	"Jobst Oetzmann",
	"Malte Ludin",
	"Christopher Buchholz",
	"Mercedes García Guevara",
	"Jonathan Sagall",
	"Gholam Reza Ramezani",
	"Michale Boganim",
	"Nils Willbrandt",
	"Volker Koepp",
	"Boguslaw Linda",
	"Anna Wieczur-Bluszcz",
	"Spiros Stathoulopoulos",
	"Ana Guevara",
	"Leticia Jorge",
	"Filip Marczewski",
	"Franziska Meyer Price",
	"Simon Staho",
	"Árpád Bogdán",
	"Seng Tat Liew",
	"Olmo Omerzu",
	"Ishtar Yasin Gutierrez",
	"Ben Hackworth",
	"Walter Bockmayer",
	"Peter Sempel",
	"Georg Marischka",
	"Eugen York",
	"Gustav Ehmck",
	"Frank Strecker",
	"Markus Fischer",
	"Tom Shoval",
	"Edoardo Winspeare",
	"Minh Nguyen-Vo",
	"Anna Kazejak",
	"Leila Kilani",
	"Jose Luis Valle",
	"Nikolaus Leytner",
	"Paul Smaczny",
	"Marianne Rosenbaum",
	"Maria Stodtmeier",
	"Till Harms",
	"Peter Vogel",
	"Isabel Kleefeld",
	"Hermann Leitner",
	"Joachim Lang",
	"Isabelle Stever",
	"Thomas Sieben",
	"Sylke Enders",
	"Volker von Collande",
	"Armin Maiwald",
	"Auraeus Solito",
	"Willy Bogner",
	"Dieter Meier",

	"Kai Christiansen",
	"Irmgard von zur Mühlen",
	"Irene Langemann",
	"Jürgen Brühns",
	"Alexander von Eschwege",
];
const Search = () => {
	const dispatch = useDispatch();
	const searchResults = useSelector(
		(state) => state.root.movieReducer?.searchResult
	);
	const [query, setQuery] = useState(defaultQuery);
	const [genres, setGenres] = useState([]);
	const [actors, setActors] = useState([]);
	const [directors, setDirectors] = useState([]);
	const [isQueryValid, setIsQueryValid] = useState(false);
	const handleChange = (e) => {
		const name = e.target.name;
		const value = e.target.value;
		setQuery({ ...query, [name]: value });
	};

	const checkValidity = () => {
		if (
			query.title !== "" ||
			query.year ||
			genres.length > 0 ||
			actors.length > 0 ||
			directors.length > 0
		) {
			setIsQueryValid(true);
		} else {
			setIsQueryValid(false);
		}
	};
	useEffect(() => {
		checkValidity();
	}, [query, genres, actors, directors]);
	const handleSearch = (e) => {
		e.preventDefault();
		const finishedQuery = { ...query, genres, actors, directors };
		if (isQueryValid) {
			dispatch(searchAdvMovies(finishedQuery));
		}
	};
	return (
		<div className="searchMain">
			<h1 style={{ textAlign: "center" }}>Advanced Search</h1>
			<TextField
				fullWidth
				focused
				label="Search"
				size="small"
				name="title"
				placeholder="Movie title"
				value={query.title}
				onChange={(e) => handleChange(e)}
			/>
			<div className="secondOpt">
				<MultiSelect
					className="searchGenres"
					onChange={setGenres}
					name="genres"
					searchable
					data={defaultGenres}
					placeholder="Choose Genres"
					label="Genres"
					value={genres}
				/>
				<NumberInput
					className="searchYear"
					label="Year"
					value={query.year}
					max={new Date().getFullYear()}
					step={1}
					onChange={(val) => setQuery({ ...query, year: val })}
				/>
			</div>
			<div className="secondOpt">
				<MultiSelect
					limit={200}
					className="searchGenres"
					onChange={setActors}
					name="actors"
					searchable
					data={defaultActors}
					placeholder="Searching displays more actors"
					label="Actors"
					value={actors}
				/>
				<MultiSelect
					limit={200}
					className="searchYear"
					onChange={setDirectors}
					name="directors"
					searchable
					data={defaultDirectors}
					placeholder="Searching displays more directors"
					label="Directors"
					value={directors}
				/>
			</div>
			<div style={{ textAlign: "center" }}>
				{isQueryValid && (
					<Text
						onClick={() => {
							setGenres([]);
							setDirectors([]);
							setActors([]);
							setQuery(defaultQuery);
						}}
						className="clearBtn"
					>
						Clear
					</Text>
				)}
				<Button
					disabled={!isQueryValid}
					className="searchBtn"
					onClick={(e) => handleSearch(e)}
				>
					Search
				</Button>
			</div>

			{searchResults && searchResults.length > 0 && (
				<div>
					<Paper
						style={{
							padding: "0px 20px",
							paddingTop: "20px",
						}}
					>
						{searchResults.map((movie) => {
							return (
								<React.Fragment key={movie._id}>
									<Grid
										style={{ marginBottom: "0px" }}
										container
										wrap="nowrap"
									>
										<Grid item xs zeroMinWidth>
											<h1
												style={{
													textAlign: "center",
												}}
											>
												<Link
													to={`/movie/${movie._id}`}
												>
													{movie.title}
												</Link>
											</h1>

											<p
												style={{
													textAlign: "left",
												}}
											>
												{movie.info.plot}
											</p>
										</Grid>
									</Grid>
									<Divider
										variant="fullWidth"
										style={{ margin: "15px 0" }}
									/>
								</React.Fragment>
							);
						})}
					</Paper>
				</div>
			)}
		</div>
	);
};

export default Search;
